### PR TITLE
fix(ipv6): allow disabling IPv6 resolve

### LINKED ISSUE #6017: request help: Provide a configuration to disable ipv6
### Issue description

When APISIX parses the upstream host, it may be parsed as `ipv6` or `ipv4`. 
Hope to provide a configuration in `config.yaml` to have the ability to disable `ipv6`.

### Environment

- apisix version (cmd: `apisix version`): master
- OS (cmd: `uname -a`): centos 7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.*
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.14
- apisix-dashboard version, if have: - 
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner): -
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): -

### PR DESCRIPTION
**Pull request by leslie-tsang**
### What this PR does / why we need it:

Sync `apisix.enable_ipv6` config to the generated `nginx.conf` resolver section

fix #6017 

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

File: apisix/cli/ops.lua [hunk 1]
```diff
@@ -552,6 +552,7 @@ Please modify "admin_key" in conf/config.yaml .
         admin_server_addr = admin_server_addr,
         control_server_addr = control_server_addr,
         prometheus_server_addr = prometheus_server_addr,
+        enable_ipv6 = yaml_conf.apisix.enable_ipv6,
```
Comment (spacewander) [inline apisix/cli/ops.lua:555]: The enable_ipv6 is already imported below

**Review by tzssangglass — APPROVED** [review]

**Review by tokers — APPROVED** [review]

File: apisix/core/dns/client.lua [hunk 2]
```diff
@@ -130,7 +130,7 @@ end
 
 
 function _M.new(opts)
-    opts.ipv6 = true
+    opts.ipv6 = opts.ipv6 or true
```
Comment (spacewander) [inline apisix/core/dns/client.lua:133]: Why not `= local_conf.apisix.enable_ipv6`? And we need a test for it.

Comment (leslie-tsang) [reply apisix/core/dns/client.lua:133]: > Why not = local_conf.apisix.enable_ipv6?

IMO, `= local_conf.apisix.enable_ipv6` is a breaking change, Imagine a scenario where a third party or serverless plugin uses this function to parse ipv6, this change will causes an unexpected behavior, I wander if this is a fictitious demand.
Do let me know WDYT. Thanks.

> And we need a test for it.

Sure, I will add it.

Comment (spacewander) [reply apisix/core/dns/client.lua:133]: We can use
```
if opts.ipv6 == nil then
  ...
end
```
so user can specify the ipv6 option to overwrite the default one.

AFAIK, we don't promise the DNS client always handles IPv6 query and the `enable_ipv6` is enabled by default, so it's not a break change. (Even if users don't  consider it is a bug fix)

Comment (leslie-tsang) [reply apisix/core/dns/client.lua]: OK, I will add test case for it in next PR

File: apisix/core/dns/client.lua [hunk 3]
```diff
@@ -130,7 +132,22 @@ end
 
 
 function _M.new(opts)
-    opts.ipv6 = true
+    local local_conf = config_local.local_conf()
+
+    if opts.ipv6 == nil then
```
Comment (spacewander) [inline apisix/core/dns/client.lua:137]: I spend some time digging into it. Look like it should be `enable_ipv6`, and it only works with the nameserver. See http://kong.github.io/lua-resty-dns-client/modules/resty.dns.client.html#init

This field is incorrect from the beginning...

Comment (leslie-tsang) [reply apisix/core/dns/client.lua]: 🤣 done

**Review by spacewander — APPROVED** [review]
