### PR TITLE
fix: only log response body when `include_resp_body`  is enabled

### LINKED ISSUE #12537: Bug: The http-logger plugin has 'include_resp_body' set to false, but the response body still appears in the response.
### Current Behavior

APISIX Version: 3.12.0
http-logger config:

```json
"http-logger": {
    "timeout": 3,
    "inactive_timeout": 5,
    "retry_delay": 1,
    "concat_method": "json",
    "uri": "http://xxxx:xxxx/v1/log/insert",
    "ssl_verify": false,
    "include_req_body": false,
    "max_retry_count": 0,
    "batch_max_size": 1000,
    "buffer_duration": 60,
    "include_resp_body": false,
    "name": "aiap-ai-http-logger"
}
```

receive:
[{"route_id":"global_llm","client_ip":"xxxx","start_time":1754878029272,"service_id":"","upstream_latency":3222,"apisix_latency":11.000040054321,"request":{"headers":{"authorization":"Bearer xx","content-length":"146","postman-token":"xx","host":"xx:xx","accept":"*/*","accept-encoding":"gzip, deflate, br","cache-control":"no-cache","user-agent":"PostmanRuntime/7.45.0","x-request-id":"xx","connection":"keep-alive","content-type":"application/json"},"size":504,"method":"POST","uri":"/v1/chat/completions","url":"http://xx:xx/v1/chat/completions","querystring":{}},"latency":3233.0000400543,"upstream":"xx:xx","response":{"status":200,"body":"{\"id\":\"xx\",\"object\":\"chat.completion\",\"created\":1754878029,\"model\":\"xx\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"reasoning_content\":\"\\n好的，用户发来“你好”，这是一个常见的问候语。首先，我需要友好回应，保持亲切的语气。用户可能希望开始一段对话，或者有具体问题需要帮助。接下来，我应该用中文回复，并主动询问他们需要什么帮助，以促进进一步交流。同时，注意保持简洁和自然，避免使用过于复杂的句子。现在，我需要组织一个合适的回应，比如“你好！有什么我可以帮助你的吗？”这样既回应了问候，又提供了帮助的意愿，符合用户的需求。\\n\",\"content\":\"\\n\\n你好！有什么我可以帮助你的吗？\",\"tool_calls\":[]},\"logprobs\":null,\"finish_reason\":\"stop\",\"stop_reason\":null}],\"usage\":{\"prompt_tokens\":9,\"total_tokens\":130,\"completion_tokens\":121,\"prompt_tokens_details\":null},\"prompt_logprobs\":null}","headers":{"x-request-id":"xx","transfer-encoding":"chunked","connection":"close","server":"APISIX/3.12.0","date":"Mon, 11 Aug 2025 02:07:12 GMT","content-type":"application/json"},"size":1261},"server":{"hostname":"xx","version":"3.12.0"}}]

### Expected Behavior

the response should not appear response.body

### Error Logs

_No response_

### Steps to Reproduce

1. Run APISIX via Docker image
2. New a route with http-logger.

```
"http-logger": {
    "timeout": 3,
    "inactive_timeout": 5,
    "retry_delay": 1,
    "concat_method": "json",
    "uri": "http://xxxx:xxxx/v1/log/insert",
    "ssl_verify": false,
    "include_req_body": false,
    "max_retry_count": 0,
    "batch_max_size": 1000,
    "buffer_duration": 60,
    "include_resp_body": false,
    "name": "aiap-ai-http-logger"
}
```

3. use a service receive response

### Environment

- APISIX version (3.12.0):
- Operating system (linux):
- OpenResty / Nginx version (1.27.1.1):
- etcd version, if relevant (3.5.21):
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by LiteSun**
### Description
This PR fixes an issue where, when both file-logger and http-logger plugins are configured on the same route, enabling include_resp_body in file-logger would also cause http-logger to log the response body, even if include_resp_body was disabled for http-logger.

#### Which issue(s) this PR fixes:

fix #12537

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by AlinsRan — DISMISSED** [review]

File: apisix/utils/log-util.lua [hunk 1]
```diff
@@ -199,7 +199,9 @@ local function get_full_log(ngx, conf)
     }
 
     if ctx.resp_body then
```
Comment (nic-6443) [inline apisix/utils/log-util.lua]: I think we can remove this check, just check `conf.include_resp_body` is enough.

**Review by nic-6443 — APPROVED** [review]

**Review by AlinsRan — APPROVED** [review]
