### PR TITLE
fix(prometheus): disable features when prometheus plugin is turned off

### LINKED ISSUE #11046: bug: Disable All Prometheus-related Features When Prometheus Plugin is Turned Off
### Current Behavior

The Prometheus plugin is a crucial component for observability within Apache APISIX. However, I've encountered an issue where, even after the Prometheus plugin is disabled, all features related to Prometheus are not entirely shut down. This behavior could lead to unexpected performance impacts and data leakage.

Upon disabling the Prometheus plugin, certain Prometheus-related functionalities continue to operate, suggesting that not all components associated with the plugin are fully turned off.

### Expected Behavior

When the Prometheus plugin is disabled, all functionalities and metrics associated with Prometheus should be completely deactivated to ensure no unnecessary overhead or data exposure.

### Error Logs

_No response_

### Steps to Reproduce

1. Enable the Prometheus plugin in Apache APISIX.
2. Generate some traffic and observe Prometheus metrics being collected.
3. Disable the Prometheus plugin.
4. Observe that metrics or features associated with Prometheus are still active or being collected.

### Environment

- APISIX version (run `apisix version`): 3.8.0
- Operating system (run `uname -a`): Linux 4f398f8410bc 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.25.3.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by shreemaan-abhishek**
### Description

This PR allows disabling the export server when prometheus is removed from plugins list in config.yaml and then the plugin reload api is called.

Fixes #11046 

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: t/cli/test_prometheus_reload.sh [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+
+. ./t/cli/common.sh
+
+git checkout conf/config.yaml
+
+sleep 1
```
Comment (starsz) [inline t/cli/test_prometheus_reload.sh:24]: I think we don't need to sleep here.

File: apisix/plugins/prometheus/exporter.lua [hunk 2]
```diff
@@ -112,6 +113,9 @@ function _M.http_init(prometheus_enabled_in_stream)
     -- todo: support hot reload, we may need to update the lua-prometheus
     -- library
     if ngx.get_phase() ~= "init" and ngx.get_phase() ~= "init_worker"  then
+        if prometheus_bkp ~= nil then
```
Comment (starsz) [inline apisix/plugins/prometheus/exporter.lua:116]: prometheus_bkp would be better.

File: apisix/plugin.lua [hunk 3]
```diff
@@ -344,6 +346,15 @@ function _M.load(config)
             if not ok then
                 core.log.error("failed to load plugins: ", err)
             end
+
+            local enabled = core.table.array_find(http_plugin_names, "prometheus") ~= nil
+            local active  = exporter.get_prometheus() ~= nil
```
Comment (starsz) [inline apisix/plugin.lua:351]: I think we don't need to get the active status.
Since the `exporter.destroy` is harmless.

File: t/plugin/prometheus4.t [hunk 4]
```diff
@@ -277,3 +277,140 @@ apisix_http_latency_bucket\{type="upstream",route="1",service="",consumer="",nod
...
+
+=== TEST 11: remove prometheus -> reload -> send batch request -> add prometheus for next tests
+--- config
+    location /t {
+        content_by_lua_block {
+            local http = require "resty.http"
+            local httpc = http.new()
+
+            local t = require("lib.test_admin").test
+                    ngx.sleep(0.1)
```
Comment (starsz) [inline t/plugin/prometheus4.t:343]: Code style.

File: t/plugin/prometheus4.t [hunk 5]
```diff
@@ -277,3 +277,140 @@ apisix_http_latency_bucket\{type="upstream",route="1",service="",consumer="",nod
...
+            require("lib.test_admin").set_config_yaml(data)
+            local code, _, org_body = t('/v1/plugins/reload', ngx.HTTP_PUT)
+            local code, body = t('/batch-process-metrics',
+                 ngx.HTTP_GET
+                )
+
+            ngx.status = code
+            ngx.say(body)
+
+
```
Comment (starsz) [inline t/plugin/prometheus4.t:368]:
```suggestion
```

File: t/plugin/prometheus4.t [hunk 6]
```diff
@@ -277,3 +277,140 @@ apisix_http_latency_bucket\{type="upstream",route="1",service="",consumer="",nod
...
+    example-plugin:
+        val: 1
+        ]]
+            require("lib.test_admin").set_config_yaml(data)
+            local code, _, org_body = t('/v1/plugins/reload', ngx.HTTP_PUT)
+            local code, body = t('/batch-process-metrics',
+                 ngx.HTTP_GET
+                )
+
+            ngx.status = code
```
Comment (starsz) [inline t/plugin/prometheus4.t:365]: Why the response code is 404 ?

Comment (shreemaan-abhishek) [reply t/plugin/prometheus4.t:365]: not sure I copied this test from here: https://github.com/apache/apisix/blob/e36db170f7e7d3ca0901bedd66ff175f55557250/t/plugin/prometheus2.t#L337C1-L389C20 😬 

I tried to find the reason but could not.

File: apisix/plugin.lua (hunk 3 above)
Comment (shreemaan-abhishek) [reply apisix/plugin.lua:351]: you are right

File: apisix/plugins/prometheus/exporter.lua (hunk 2 above)
Comment (shreemaan-abhishek) [reply apisix/plugins/prometheus/exporter.lua]: done

File: t/cli/test_prometheus_reload.sh (hunk 1 above)
Comment (shreemaan-abhishek) [reply t/cli/test_prometheus_reload.sh:24]: done

File: t/plugin/prometheus4.t (hunk 6 above)
Comment (starsz) [reply t/plugin/prometheus4.t:365]: I know. The 404 is from upstream(1980) not from apisix.
Since we don't have any handler of `batch-process-metrics` in [lib/server.lua](https://github.com/apache/apisix/blob/master/t/lib/server.lua)

File: apisix/plugin.lua (hunk 3 above)
Comment (shreemaan-abhishek) [reply apisix/plugin.lua:351]: no I think the second if check needs the `active` status. Consider this case:

- apisix is running with prometheus active and enabled
- hit plugin reload

In this case `enabled == true` and `active == true`. But we need not call `http_init()` in prometheus because it is already running during this operation.

File: t/plugin/prometheus4.t (hunk 6 above)
Comment (shreemaan-abhishek) [reply t/plugin/prometheus4.t:365]: ahhh yes! you are right.

File: apisix/plugin.lua (hunk 3 above)
Comment (starsz) [reply apisix/plugin.lua:351]: Got it.

**Review by starsz — APPROVED** [review]

**Review by moonming — APPROVED** [review]

File: apisix/plugins/prometheus/exporter.lua [hunk 7]
```diff
@@ -545,4 +552,13 @@ function _M.get_prometheus()
     return prometheus
 end
 
+
+function _M.destroy()
+    if prometheus ~= nil then
+        prometheus_bkp = core.table.deepcopy(prometheus)
```
Comment (nic-6443) [inline apisix/plugins/prometheus/exporter.lua:558]: Why use `deepcopy`? Using the original object directly should be fine.
