### PR TITLE
fix: etcd data sync exception

### LINKED ISSUE #8648: bug: attempt to index local 'item' (a boolean value)
### Current Behavior

Newly installed apisix cluster throws following exception:

```
2023/01/10 10:03:19 [error] 54#54: *1312995 [lua] config_etcd.lua:662: failed to fetch data from etcd: /usr/local/apisix/apisix/core/config_util.lua:99: attempt to index local 'item' (a boolean value)
stack traceback:
        /usr/local/apisix/apisix/core/config_util.lua:99: in function 'fire_all_clean_handlers'
        /usr/local/apisix/apisix/core/config_etcd.lua:379: in function 'sync_data'
        /usr/local/apisix/apisix/core/config_etcd.lua:609: in function </usr/local/apisix/apisix/core/config_etcd.lua:599>
        [C]: in function 'xpcall'
        /usr/local/apisix/apisix/core/config_etcd.lua:599: in function </usr/local/apisix/apisix/core/config_etcd.lua:577>,  etcd key: /apisix/routes, context: ngx.timer
```

### Expected Behavior

Running without former issue.

### Error Logs

2023/01/10 10:06:21 [error] 48#48: *1334880 [lua] config_etcd.lua:662: failed to fetch data from etcd: /usr/local/apisix/apisix/core/config_util.lua:99: attempt to index local 'item' (a boolean value)
stack traceback:
        /usr/local/apisix/apisix/core/config_util.lua:99: in function 'fire_all_clean_handlers'
        /usr/local/apisix/apisix/core/config_etcd.lua:379: in function 'sync_data'
        /usr/local/apisix/apisix/core/config_etcd.lua:609: in function </usr/local/apisix/apisix/core/config_etcd.lua:599>
        [C]: in function 'xpcall'
        /usr/local/apisix/apisix/core/config_etcd.lua:599: in function </usr/local/apisix/apisix/core/config_etcd.lua:577>,  etcd key: /apisix/routes, context: ngx.timer
2023/01/10 10:06:21 [error] 50#50: *1334917 [lua] config_etcd.lua:662: failed to fetch data from etcd: /usr/local/apisix/apisix/core/config_util.lua:99: attempt to index local 'item' (a boolean value)
stack traceback:
        /usr/local/apisix/apisix/core/config_util.lua:99: in function 'fire_all_clean_handlers'
        /usr/local/apisix/apisix/core/config_etcd.lua:379: in function 'sync_data'
        /usr/local/apisix/apisix/core/config_etcd.lua:609: in function </usr/local/apisix/apisix/core/config_etcd.lua:599>
        [C]: in function 'xpcall'
        /usr/local/apisix/apisix/core/config_etcd.lua:599: in function </usr/local/apisix/apisix/core/config_etcd.lua:577>,  etcd key: /apisix/routes, context: ngx.timer
2023/01/10 10:06:22 [error] 56#56: *1334983 [lua] config_etcd.lua:662: failed to fetch data from etcd: /usr/local/apisix/apisix/core/config_util.lua:99: attempt to index local 'item' (a boolean value)
stack traceback:
        /usr/local/apisix/apisix/core/config_util.lua:99: in function 'fire_all_clean_handlers'
        /usr/local/apisix/apisix/core/config_etcd.lua:379: in function 'sync_data'
        /usr/local/apisix/apisix/core/config_etcd.lua:609: in function </usr/local/apisix/apisix/core/config_etcd.lua:599>
        [C]: in function 'xpcall'
        /usr/local/apisix/apisix/core/config_etcd.lua:599: in function </usr/local/apisix/apisix/core/config_etcd.lua:577>,  etcd key: /apisix/routes, context: ngx.timer

### Steps to Reproduce

1. Install apisix cluster with following images: `apache/apisix:3.1.0-debian`
2. Running at least **4** hours;
3. Not sure this issue will be throwed as previous.

### Environment

- APISIX version (run `apisix version`): 3.1.0 (3.1.0-debian official docker image)
- Operating system (run `uname -a`): Linux apisix-v3-0-58d694d79d-8567j 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"boot_time":1672910773,"etcd_version":"3.4.0","hostname":"apisix-v3-0-58d694d79d-8567j","version":"3.1.0","id":"c978a662-9041-4e7b-9a4d-d5bea6ef32f9"}
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by jobop**
### Description

Fixes https://github.com/apache/apisix/issues/8492
Fix #8648

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by jobop — COMMENTED** [review]
When the key is deleted, the item will be set to false.

File: apisix/core/config_util.lua [hunk 1]
```diff
@@ -96,6 +96,10 @@ end
 
 -- fire all clean handlers added by add_clean_handler.
 function _M.fire_all_clean_handlers(item)
+    -- When the key is deleted, the item will be set to false.
```
Comment (jobop) [inline apisix/core/config_util.lua:99]: When the key is deleted, the item will be set to false.

**Review by spacewander — COMMENTED** [review]
Is it possible to add a test case to avoid regression? For example, we can add a test in https://github.com/apache/apisix/blob/master/t/node/healthcheck-stop-checker.t

**Comment by jobop** [comment]
> 

yes,i hava add some test cases

**Comment by jobop** [comment]
> Is it possible to add a test case to avoid regression? For example, we can add a test in https://github.com/apache/apisix/blob/master/t/node/healthcheck-stop-checker.t

yes,i hava add some test cases

File: t/core/config_util.t [hunk 2]
```diff
@@ -103,6 +108,9 @@ __DATA__
             local item, idx1, idx2 = setup()
             util.cancel_clean_handler(item, idx1)
             util.fire_all_clean_handlers(item)
+
+            local item = setup_to_false()
+            util.fire_all_clean_handlers(item)
```
Comment (spacewander) [inline t/core/config_util.t:113]: Is it possible to test this bug by deleting a key as you described in the issue? It would be great if we could cover it via an integration test which is more readable.

**Comment by zhangliweixyz** [comment]
I had the same problem, and Is there any way to solve this problem？

**Comment by spacewander** [comment]
@zhangliweixyz 
Let's wait for @jobop to update the PR.

**Comment by basuotian** [comment]
we had the same problem, it occur especially in etcd_auto_compaction_mode=revision during we do a lot of update/delete operation to apisixroute

**Comment by spacewander** [comment]
Since people keep asking about it, we can merge it first.

**Review by spacewander — APPROVED** [review]

**Comment by oyiadin** [comment]
maybe related: https://github.com/apache/apisix/issues/8648#issuecomment-1475240703

**Review by leslie-tsang — APPROVED** [review]
