### PR TITLE
test: make t/chaos/kill-chaos.t stable

### LINKED ISSUE #4437: test not stable: t/chaos/kill-etcd
### Issue description

https://github.com/apache/apisix/pull/4436/checks?check_run_id=2844856100
```
=== RUN   TestGetSuccessWhenEtcdKilled/ingress_bandwidth_per_second_not_change_much
    kill-etcd_test.go:122: bandwidth before: 1176.000000, after: 1176.000000
    kill-etcd_test.go:123: duration before: 5.005692, after: 7.034161
    kill-etcd_test.go:124: bps before: 234.932532, after: 167.184126
=== CONT  TestGetSuccessWhenEtcdKilled
    kill-etcd_test.go:125: 
        Expected
            <bool>: false
        to be true
=== CONT  TestGetSuccessWhenEtcdKilled/ingress_bandwidth_per_second_not_change_much
    testing.go:975: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): master

### PR DESCRIPTION
**Pull request by Yiyiyimu**
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>

### What this PR does / why we need it:
fix #4437 

Can not reproduce in the local environment. Try to make it stable by receiving more requests in a certain time period, to make bandwidth-per-second comparison more stable.

Also changed to egress bps comparison as measurement, since egress is what expected to be the same.

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by spacewander — APPROVED** [review]

File: t/chaos/utils.go [hunk 1]
```diff
@@ -158,16 +158,16 @@ func getPrometheusMetric(e *httpexpect.Expect, g *WithT, key string) string {
 	return targetSlice[1]
 }
 
-func getIngressBandwidthPerSecond(e *httpexpect.Expect, g *WithT) (float64, float64) {
-	key := "apisix_bandwidth{type=\"ingress\","
+func getEgressBandwidthPerSecond(e *httpexpect.Expect, g *WithT) (float64, float64) {
```
Comment (tokers) [inline t/chaos/utils.go:161]: Why even the semantics of this function was changed?

Comment (Yiyiyimu) [reply t/chaos/utils.go:161]: > changed to egress bps comparison as measurement, since egress is what expected to be the same

**Review by tokers — APPROVED** [review]
