### PR TITLE
fix: the jwt plugin does not handle the case where `exp` is empty. (#…

### LINKED ISSUE #2649: bug: The jwt plugin does not handle the case where `exp` is empty
https://github.com/apache/apisix/commit/27875e57901ff1bbb1161bbd55364ecef2990e27#r43958477

### PR DESCRIPTION
**Pull request by tzssangglass**
…2649)

fix #2649

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Review by membphis — COMMENTED** [review]
missing test case

**Comment by membphis** [comment]
please update the test case

**Comment by tzssangglass** [comment]
ok

File: apisix/plugins/jwt-auth.lua [hunk 1]
```diff
@@ -53,7 +53,7 @@ local consumer_schema = {
             enum = {"HS256", "HS512", "RS256"},
             default = "HS256"
         },
-        exp = {type = "integer", minimum = 1},
+        exp = {type = "integer", minimum = 1, default = 86400},
```
Comment (membphis) [inline apisix/plugins/jwt-auth.lua:56]: and we need to add a test case to check the default value, we need to sure it works.

and we need a test case for this case: https://github.com/apache/apisix/issues/2649

we need to sure we fixed this bug.

Comment (tzssangglass) [reply apisix/plugins/jwt-auth.lua:56]: Do you mean that when jwt expires (`exp` = `default` value), need to verify that jwt is invalid?

File: t/plugin/jwt-auth.t [hunk 2]
```diff
@@ -1140,3 +1140,48 @@ base64_secret required but the secret is not in base64 format
 [error]
 --- request
 GET /t
+
```
Comment (tzssangglass) [inline t/plugin/jwt-auth.t:1143]: @membphis does this test case cover the situation you mentioned
https://github.com/apache/apisix/pull/2657#discussion_r519373662

File: t/plugin/jwt-auth.t [hunk 3]
```diff
@@ -1140,3 +1140,48 @@ base64_secret required but the secret is not in base64 format
...
+
+
+=== TEST 50: when the exp value is not set,make sure the default value(86400) works
```
Comment (tzssangglass) [inline t/plugin/jwt-auth.t:1146]: @membphis does this test case cover the situation you mentioned
https://github.com/apache/apisix/pull/2657#discussion_r519373662

Comment (tzssangglass) [inline t/plugin/jwt-auth.t:1146]: @membphis does this test case cover the situation you mentioned
https://github.com/apache/apisix/pull/2657#discussion_r519373662

File: t/plugin/jwt-auth.t [hunk 4]
```diff
@@ -1140,3 +1140,73 @@ base64_secret required but the secret is not in base64 format
 [error]
 --- request
 GET /t
+
+
+
+=== TEST 50: when the exp value is not set, make sure the default value(86400) works
```
Comment (tzssangglass) [inline t/plugin/jwt-auth.t:1146]: @membphis do these two cases cover the scenarios you mention?
I'm not sure if the TEST51 is elegant enough.

File: t/plugin/jwt-auth.t [hunk 5]
```diff
@@ -1140,3 +1140,73 @@ base64_secret required but the secret is not in base64 format
...
+
+
+
+=== TEST 51: when the exp value is not set, sign jwt use the default value(86400)
+--- config
+    location /t {
+        content_by_lua_block {
+            local t = require("lib.test_admin").test
+            local code, body, res_data = t('/apisix/plugin/jwt/sign?key=exp-not-set',
+                ngx.HTTP_GET, nil, nil)
```
Comment (Firstsawyou) [inline t/plugin/jwt-auth.t:1197]: I think it would be better not to need nil , for example: `local code, body, res_data = t('/apisix/plugin/jwt/sign?key=exp-not-set', ngx.HTTP_GET)` . What do you think？

Comment (tzssangglass) [reply t/plugin/jwt-auth.t:1197]: let me try

**Review by nic-chen — APPROVED** [review]

**Review by membphis — APPROVED** [review]
