### PR TITLE
fix: the client verify flag might not be set

### LINKED ISSUE #6896: bug: mtls does not take effect
### Current Behavior

配置 ssl 资源同时配置了 client.ca 和 client.depth 参数，在upstream配置了client_cert和client_key。使用浏览器访问时并未配置对应证书，第一次响应返回400，查看日志发现错误：client certificate was not present，此现象正常；紧接着第二次再次访问发现可以获取到后置服务正常响应。

### Expected Behavior

期望使用浏览器在未携带对应双向认证证书时，不能正常获取到响应结果。

### Error Logs

client certificate was not present

### Steps to Reproduce

1.配置路由并添加upstream，在upstream中配置client_cert和client_key
2.配置 ssl 资源同时配置了 client.ca 和 client.depth 参数
3.使用谷歌浏览器访问，第一次响应400，第二次正常获取到结果

### Environment

- APISIX version (run `apisix version`): V2.8
- Operating system (run `uname -a`):  Centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by spacewander**
A more suitable way is to reject client TLS handshake directly, just
like what Go has done.

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Description

Fixes #6896

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/init.lua [hunk 1]
```diff
@@ -313,7 +314,13 @@ end
 
 
 local function verify_tls_client(ctx)
-    if ctx and ctx.ssl_client_verified then
+    local matched = router.router_ssl.match_and_set(ctx, true)
```
Comment (membphis) [inline apisix/init.lua:317]: need to capture the `err` message

File: apisix/init.lua [hunk 2]
```diff
@@ -313,7 +314,13 @@ end
...
+    if not matched then
+        return true
```
Comment (membphis) [inline apisix/init.lua:319]: little confused, we should return false, all right?

File: apisix/init.lua (hunk 1 above)
Comment (spacewander) [reply apisix/init.lua:317]: match_and_set will return `err` when it fails to match the SSL certificate, but this is not considered an error here because both non-TLS and TLS will execute this function.

File: apisix/init.lua (hunk 2 above)
Comment (spacewander) [reply apisix/init.lua:319]: Return true means the verification is successful when this function is called with non-TLS request.

Comment (membphis) [reply apisix/init.lua:319]: got it, many thx

**Review by membphis — APPROVED** [review]
LGTM

File: apisix/init.lua [hunk 3]
```diff
@@ -350,14 +357,14 @@ end
...
 
-    if not verify_tls_client(ngx_ctx.api_ctx) then
-        return core.response.exit(400)
-    end
-
     -- always fetch table from the table pool, we don't need a reused api_ctx
     local api_ctx = core.tablepool.fetch("api_ctx", 0, 32)
     ngx_ctx.api_ctx = api_ctx
 
+    if not verify_tls_client(ngx_ctx.api_ctx) then
```
Comment (membphis) [inline apisix/init.lua:364]: we can use `api_ctx` here

File: apisix/init.lua [hunk 4]
```diff
@@ -870,15 +877,15 @@ function _M.stream_preread_phase()
...
-    if not verify_tls_client(ngx_ctx.api_ctx) then
-        return ngx_exit(1)
-    end
-
     if not api_ctx then
         api_ctx = core.tablepool.fetch("api_ctx", 0, 32)
         ngx_ctx.api_ctx = api_ctx
     end
 
+    if not verify_tls_client(ngx_ctx.api_ctx) then
```
Comment (membphis) [inline apisix/init.lua:885]: ditto

**Comment by tokers** [comment]
Anyway to test the fix?

**Comment by spacewander** [comment]
> Anyway to test the fix?

Not so easy to do it.

**Comment by tokers** [comment]
> > Anyway to test the fix?
> 
> 
> 
> Not so easy to do it.

What about writing the case in shell? And use curl to send two requests.

**Review by tokers — APPROVED** [review]

**Review by membphis — APPROVED** [review]
