### PR TITLE
fix: define destroy() to close protos

### LINKED ISSUE #8519: bug: grpc-transcode do not close core.config instance when the plugin is unloaded
### Current Behavior

https://github.com/apache/apisix/blob/5f071049777facc1bc0b690ede3928f9da6b49c5/apisix/plugins/grpc-transcode.lua#L121

https://github.com/apache/apisix/blob/5f071049777facc1bc0b690ede3928f9da6b49c5/apisix/plugins/grpc-transcode/proto.lua#L253-L256

This plugin does not define `destroy()`.

config instance of etcd would create a timer to refresh `"/protos"` resource. We need to close the instance in `destroy()`, which in turn closes the timer.

### Expected Behavior

_No response_

### Error Logs

_No response_

### Steps to Reproduce

```bash 
curl http://127.0.0.1:9180/apisix/admin/plugins/reload -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT
```

### Environment

- APISIX version (run `apisix version`): master branch
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by kingluo**
### Description

Fixes #8519

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/plugins/grpc-transcode/proto.lua [hunk 1]
```diff
@@ -270,5 +270,10 @@ function _M.init()
     end
 end
 
+function _M.destroy()
+    if protos then
+        protos:close()
```
Comment (spacewander) [inline apisix/plugins/grpc-transcode/proto.lua:275]: Could we add a test to ensure the `close` is called? For instance, via injecting some code.

File: t/plugin/grpc-transcode-reload-bugfix.t [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+                return
+            end
+
+            ngx.sleep(2)
+            if close_cnt ~= 1 then
+                ngx.status = 500
+            end
+        }
+    }
+--- timeout: 3
```
Comment (spacewander) [inline t/plugin/grpc-transcode-reload-bugfix.t:74]: The default timeout is already 3 seconds. We don't need to repeat it.

**Review by spacewander — APPROVED** [review]

**Review by soulbird — APPROVED** [review]
