### PR TITLE
fix(etcd): avoid getting with prefix

### LINKED ISSUE #2771: bug: admin api matches config ID by prefix
### Issue description
Admin api appears to match config Id by prefix instead of an exact string match.

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: osx + linux

### Minimal test code / Steps to reproduce the issue
1. PUT a new upstream with id: abc
2. GET upstream by id: ab

### What's the actual result? (including assertion message & call stack if applicable)
The upstream abc is returned.

### What's the expected result?
 A NOT_FOUND is expected here

### PR DESCRIPTION
**Pull request by spacewander**
Fix #2771.

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

File: apisix/core/etcd.lua [hunk 1]
```diff
@@ -92,17 +94,28 @@ function _M.get_format(res, realkey)
...
+
+        res.body.node = kvs_to_node(res.body.kvs[1])
+
+    else
+        -- In etcd v2, the direct key asked for is `node`, others which under this dir are `nodes`
+        -- While in v3, this structure is flatten and all keys related the key asked for are `kvs`
+        res.body.node = kvs_to_node(res.body.kvs[1])
+        if not res.body.kvs[1].value then
+            -- remove last "/" when necesary
+            if string.sub(res.body.node.key, -1, -1) == "/" then
```
Comment (tokers) [inline apisix/core/etcd.lua:114]: What about using `string.byte` here?

Comment (spacewander) [reply apisix/core/etcd.lua]: @tokers Updated

**Review by membphis — APPROVED** [review]

**Review by tokers — APPROVED** [review]
