### PR TITLE
fix(admin): use local config to fetch global rules in standalone mode

### LINKED ISSUE #12989: bug: Apisix 3.15.0 tries to connect to etcd in standalone api-driven mode (non crashing)
### Current Behavior

Hello,

after upgrading our apisix k8s deployment from `3.14.1` to `3.15.0` we are seeing new apisix warnings in the apisix pod logs that indicate that apisix is trying to connect to etcd.

We are using apisix in standalone api-driven mode without etcd, but with the apisix-ingress-controller. [1]
Hence we wouldn't expect apisix trying to connect to etcd at all.

Besides the new warning messages in the log, the setup is working fine. Nothing is crashing.

In order to resolve the bug we first tried to set the externalEtcd URL  (that is being contacted) in the `values.yaml` to empty.
```
externalEtcd:
  host: {}
```
This didn't work and apisix wasn't able to start at all.

Then we tried to set the externalEtcd URL to localhost.
```
externalEtcd:
  host:
    - 127.0.0.1:2379
```
With this setting, the dns resolve warnings for `etcd.host` disappeared, but new warnings emerged.
(posted in Error Logs)

If you need further information, I'm happy to help in any way possible.

[1] https://apisix.apache.org/docs/ingress-controller/install/#install-apisix-and-apisix-ingress-controller-standalone-api-driven-mode

### Expected Behavior

After the upgrade from apisix `3.14.1` to `3.15.0` we expected that apisix won't try to connect to etcd if configured in standalone api-driven mode using the apisix-ingress-controller.

### Error Logs

```
w.x.y.z - - [09/Feb/2026:12:22:19 +0000] a.b.c.d:9180 "PUT /apisix/admin/configs HTTP/1.1" 202 5 0.005 "-" "axios/1.13.2" - - - "http://a.b.c.d:9180"
2026/02/09 12:23:19 [warn] 53#53: *265395 [lua] health_check.lua:114: report_failure(): update endpoint: http://127.0.0.1:2379 to unhealthy, client: w.x.y.z, server: , request: "PUT /apisix/admin/configs HTTP/1.1", host: "a.b.c.d:9180", request_id: "90aa0e36dd0e416f6b8fe3c4726f80c5"
2026/02/09 12:23:19 [warn] 53#53: *265395 [lua] v3.lua:247: _request_uri(): http://127.0.0.1:2379: connection refused. Retrying, client: w.x.y.z, server: , request: "PUT /apisix/admin/configs HTTP/1.1", host: "a.b.c.d:9180", request_id: "90aa0e36dd0e416f6b8fe3c4726f80c5"
w.x.y.z - - [09/Feb/2026:12:23:19 +0000] a.b.c.d:9180 "PUT /apisix/admin/configs HTTP/1.1" 202 5 0.007 "-" "axios/1.13.2" - - - "http://a.b.c.d:9180"
2026/02/09 12:24:19 [warn] 53#53: *265395 [lua] health_check.lua:114: report_failure(): update endpoint: http://127.0.0.1:2379 to unhealthy, client: w.x.y.z, server: , request: "PUT /apisix/admin/configs HTTP/1.1", host: "a.b.c.d:9180", request_id: "e8eef6965ab87271691937c044c0b765"
2026/02/09 12:24:19 [warn] 53#53: *265395 [lua] v3.lua:247: _request_uri(): http://127.0.0.1:2379: connection refused. Retrying, client: w.x.y.z, server: , request: "PUT /apisix/admin/configs HTTP/1.1", host: "a.b.c.d:9180", request_id: "e8eef6965ab87271691937c044c0b765"
w.x.y.z - - [09/Feb/2026:12:24:19 +0000] a.b.c.d:9180 "PUT /apisix/admin/configs HTTP/1.1" 202 5 0.005 "-" "axios/1.13.2" - - - "http://a.b.c.d:9180"
2026/02/09 12:25:19 [warn] 53#53: *265395 [lua] health_check.lua:114: report_failure(): update endpoint: http://127.0.0.1:2379 to unhealthy, client: w.x.y.z, server: , request: "PUT /apisix/admin/configs HTTP/1.1", host: "a.b.c.d:9180", request_id: "e3e88e4f16ca7f9016cfb0407dca4ec0"
2026/02/09 12:25:19 [warn] 53#53: *265395 [lua] v3.lua:247: _request_uri(): http://127.0.0.1:2379: connection refused. Retrying, client: w.x.y.z, server: , request: "PUT /apisix/admin/configs HTTP/1.1", host: "a.b.c.d:9180", request_id: "e3e88e4f16ca7f9016cfb0407dca4ec0"
```
Original IPs are masked as `w.x.y.z` and `a.b.c.d`.

### Steps to Reproduce

1. Run apisix `3.15.0` in standalone api-driven mode with the apisix-ingress-controller as described in the [documentation](https://apisix.apache.org/docs/ingress-controller/install/#install-apisix-and-apisix-ingress-controller-standalone-api-driven-mode).
2. Apply a route through the apisix-ingress-controller and observe the logs for the new warning messages.
3. Downgrade apisix'es image to `3.14.1` and verify that there aren't any warning messages regarding etcd communication.

### Environment

- APISIX version (run `apisix version`):
```
apisix@stage-apisix-4r9nt:/usr/local/apisix$ apisix version  
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua version
3.15.0
```

- Operating system (run `uname -a`):
```
apisix@stage-apisix-4r9nt:/usr/local/apisix$ uname -a
Linux stage-apisix-4r9nt 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
```
apisix@stage-apisix-4r9nt:/usr/local/apisix$ openresty -V
nginx version: openresty/1.27.1.2
built by gcc 13.3.0 (Ubuntu 13.3.0-6ubuntu2~24.04) 
built with OpenSSL 3.4.1 11 Feb 2025
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_RUNTIME_VER=1.3.3 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl3/include' --add-module=../ngx_devel_kit-0.3.3 --add-module=../echo-nginx-module-0.63 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.33 --add-module=../ngx_lua-0.10.28 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.37 --add-module=../array-var-nginx-module-0.06 --add-module=../memc-nginx-module-0.20 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.16 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl3/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl3/lib' --add-module=/tmp/tmp.01qlLjeAA8/openresty-1.27.1.2/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.01qlLjeAA8/openresty-1.27.1.2/../ngx_multi_upstream_module-1.3.2 --add-module=/tmp/tmp.01qlLjeAA8/openresty-1.27.1.2/../apisix-nginx-module-1.19.3 --add-module=/tmp/tmp.01qlLjeAA8/openresty-1.27.1.2/../apisix-nginx-module-1.19.3/src/stream --add-module=/tmp/tmp.01qlLjeAA8/openresty-1.27.1.2/../apisix-nginx-module-1.19.3/src/meta --add-module=/tmp/tmp.01qlLjeAA8/openresty-1.27.1.2/../wasm-nginx-module-0.7.0 --add-module=/tmp/tmp.01qlLjeAA8/openresty-1.27.1.2/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.01qlLjeAA8/openresty-1.27.1.2/../lua-resty-events-0.2.0 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --with-http_v3_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
```

### PR DESCRIPTION
**Pull request by janiussyafiq**
### Description

In standalone mode (`config_provider: yaml`), the `get_global_rules()` function in `apisix/admin/global_rules.lua` unconditionally calls `core.etcd.get("/global_rules")` to check for duplicate plugin conflicts whenever a global rule is validated. This is triggered on every `PUT /apisix/admin/configs` request from the ingress-controller that contains a `global_rules` entry, causing repeated etcd connection errors in the logs even though etcd is not used in standalone mode.                                                                                         

Root cause: `check_conf` calls `get_global_rules()` which has no awareness of the current config provider, so it always attempts an etcd read regardless of deployment mode.                                             

Fix: guard `get_global_rules()` to return `nil` immediately when `local_conf.deployment.config_provider == "yaml"`, skipping the etcd call entirely. This is safe because returning `nil` causes `check_conf` to skip the conflict loop (already guarded by `if global_rules then`), and in standalone mode the ingress-controller is responsible for sending a consistent config atomically.                                                            

#### Which issue(s) this PR fixes:

Fixes #12989

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by Baoyuantop — DISMISSED** [review]

File: apisix/admin/global_rules.lua [hunk 1]
```diff
@@ -24,6 +24,11 @@ local ipairs   = ipairs
 local tostring = tostring
 
 local function get_global_rules()
+    local local_conf = core.config.local_conf()
+    if local_conf.deployment.config_provider == "yaml" then
```
Comment (shreemaan-abhishek) [inline apisix/admin/global_rules.lua]: `get_global_rules` is used to check if the incoming global rule conflicts with existing global rules, skipping the check entirely doesn't seem correct.

Comment (janiussyafiq) [reply apisix/admin/global_rules.lua]: that is right, good catch! should still get the global rules for standalone mode cases to prevent warning log from checking etcd. will do the fix

**Review by shreemaan-abhishek — DISMISSED** [review]

**Review by Baoyuantop — DISMISSED** [review]

File: apisix/admin/global_rules.lua [hunk 2]
```diff
@@ -24,13 +24,23 @@ local ipairs   = ipairs
...
```
Comment (nic-6443) [inline apisix/admin/global_rules.lua]: The judgment of `deployment.config_provider == "yaml"` is not comprehensive, as its value can also be json. We can encapsulate a function to determine whether the current `config_provider` is `local`.

Comment (janiussyafiq) [reply apisix/admin/global_rules.lua]: fixed

**Review by nic-6443 — APPROVED** [review]

**Comment by janiussyafiq** [comment]
https://github.com/apache/apisix/pull/13170#issuecomment-4199296306 - about the CI failure

**Review by shreemaan-abhishek — APPROVED** [review]

**Review by Baoyuantop — APPROVED** [review]
