### PR TITLE
doc: fix typo

### LINKED ISSUE #2262: bug: problems in batch-requests doc
### Issue description
1. Default timeout in [code](https://github.com/apache/apisix/blob/master/apisix/plugins/batch-requests.lua#L48) is set to 30000. but in [doc](https://github.com/apache/apisix/blob/master/apisix/plugins/batch-requests.lua#L48) it's 3000.
2. Currently user is told to disable batch-requests by removing `/conf/config.yaml`. Let's say we change it to `config-default.yaml`, but this file is not suggested to modify. How should we deal with this - customized deletion but not addition - situation?

### PR DESCRIPTION
**Pull request by Yiyiyimu**
### What this PR does / why we need it:
fix #2262 and other doc typos, including

1. fix code/doc difference of batch-request default timeout
2. update method to disable batch-request, since config.yaml and config_default.yaml is separated
3. add enum of socket_type in syslog, according to doc
4. add 'disable plugin' part to grpc-transcode and prometheus doc

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### CODE REVIEW

**Review by moonming — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

File: apisix/plugins/batch-requests.lua [hunk 1]
```diff
@@ -45,7 +45,7 @@ local req_schema = {
         timeout = {
             description = "pipeline timeout(ms)",
             type = "integer",
-            default = 30000,
+            default = 3000,
```
Comment (membphis) [inline apisix/plugins/batch-requests.lua:48]: one PR for one thing. I think you can revert this line and submit it in a new PR

Comment (juzhiyuan) [reply apisix/plugins/batch-requests.lua:48]: or write a summary about what this PR does?

Comment (Yiyiyimu) [reply apisix/plugins/batch-requests.lua]: > 1. Default timeout in [code](https://github.com/apache/apisix/blob/master/apisix/plugins/batch-requests.lua#L48) is set to 30000. but in [doc](https://github.com/apache/apisix/blob/master/apisix/plugins/batch-requests.lua#L48) it's 3000.

update `doc` is better.

_Originally posted by @membphis in https://github.com/apache/apisix/issues/2262#issuecomment-697154388_

---

Since I turned to update the doc but not the code, I think we could keep them in one PR.
And thank you @juzhiyuan I write a summary. It was too messy without the list.

Comment (membphis) [reply apisix/plugins/batch-requests.lua]: agree: update doc and keep them in one PR. 

pleaes confirm you update the doc and write a right summary ^_^

Comment (Yiyiyimu) [reply apisix/plugins/batch-requests.lua]: Write the summary in the first block of this PR. Hope I make it clear :)
