### PR TITLE
fix: keep proxy-cache different strategy response header consistency

### LINKED ISSUE #11045: bug: proxy-cache inconsistent behaviours for in-memory and on-disk caching when the cache expires
### Current Behavior

inconsistent response headers for in-memory and on-disk cache when the cache expires.

* for on disk strategy, the header shows `Apisix-Cache-Status: EXPIRED`
* for in memory strategy, the headers shows `Apisix-Cache-Status: MISS`

### Expected Behavior

Same header value for both caching strategies when the cache expires.

#### disk based caching

1. Enable `proxy-cache` on a route and configure it to use disk based caching
2. Send a few requests and observe caching in effect
3. Wait for the cache to expire after TTL and send another request, to observe `Apisix-Cache-Status: EXPIRED` header

#### in memory caching

1. Enable `proxy-cache` on a route and configure it to use disk based caching
2. Send a few requests and observe caching in effect
3. Wait for the cache to expire after TTL and send another request, to observe `Apisix-Cache-Status: MISS` header

### Environment

- APISIX version (run `apisix version`): 3.8.0

### PR DESCRIPTION
**Pull request by theweakgod**
### Description

Fixes #11045 
keep proxy-cache different strategy response header consistency

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by monkeyDluffy6017 — APPROVED** [review]

File: apisix/plugins/proxy-cache/memory_handler.lua [hunk 1]
```diff
@@ -213,11 +213,19 @@ function _M.access(conf, ctx)
     end
 
     if err then
-        core.response.set_header("Apisix-Cache-Status", "MISS")
-        if err ~= "not found" then
+        if err == "expired" then
+            core.response.set_header("Apisix-Cache-Status", "EXPIRED")
+
```
Comment (Revolyssup) [inline apisix/plugins/proxy-cache/memory_handler.lua:218]: Can you remove these empty lines?

**Review by Revolyssup — CHANGES_REQUESTED** [review]

File: apisix/plugins/proxy-cache/memory_handler.lua (hunk 1 above)
Comment (theweakgod) [reply apisix/plugins/proxy-cache/memory_handler.lua:218]: I decided to write this after seeing the example of CODE_STYLE. 
[blank-line](https://github.com/apache/apisix/blob/master/CODE_STYLE.md#blank-line)

**Review by Revolyssup — APPROVED** [review]
