### PR TITLE
fix(brotli-plugin): Skip brotli compression for upstream compressed response

### LINKED ISSUE #10739: bug: Skip brotli compression if upstream response is compressed
### Current Behavior

If the upstream response contains `Content-Encoding` header , then the data needs to be decompressed to compress it to brotli. Therefore, skipping the brotli compression for already compressed upstream data will avoid returning wrong encoded data in response from apisix.

### Expected Behavior

Apisix should not compressed `gzip` or `deflate` upstream compressed data again in `brotli`. Skipping the compression will solve the issue.

Example:
If the upstream service is returning a response in `gzip` or header `Content-Encoding: gzip`. Return the same.

### Error Logs

Not applicable.

### Steps to Reproduce

1. Build an Apisix master branch.
2. Enable brotli plugin in global rules.
3. One should have an upstream that returns a gzip or deflate encoded data.

### Environment

- APISIX version (run `apisix version`): master
- Operating system (run `uname -a`): debian 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by SilentEntity**
- Fixes #10739 (issue)
---
Skipping the `brotli` compression if the upstream response is already compressed.

## The Problem
The problem occurs when the upstream service sends compressed data/response either in `gzip` or `deflate`. Apisix tries to compress data in `brotli` which is already compressed and, in turn, returns encoded data that can not be used by the browser or application.

## Possible Solutions
There are two options to solve the problem first to skip the further compression and return with the upstream compressed response. The second is to decompress the upstream response and then compress using `brotli`, which is not viable on apisix gateway, it increases the overhead of the gateway and results in increasing latency and computation requirements.

This PR solves the Issue by skipping the `brotli` compression if the upstream response is compressed.

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/plugins/brotli.lua [hunk 1]
```diff
@@ -163,6 +163,11 @@ function _M.header_filter(conf, ctx)
         return
     end
 
+    local content_encoded = ngx_header["Content-Encoding"]
+    if content_encoded then
+        -- Don't compress if Content-Encoding is present in upstream data
+        return
+    end
```
Comment (monkeyDluffy6017) [inline apisix/plugins/brotli.lua:170]: Add a blank below

**Comment by monkeyDluffy6017** [comment]
Could you add some test cases?

**Comment by monkeyDluffy6017** [comment]
I think it's reasonable, multiple compressions may cause unnecessary trouble

**Comment by monkeyDluffy6017** [comment]
please make the ci pass

**Comment by SilentEntity** [comment]
okay, it's ready

**Comment by SilentEntity** [comment]
The typo is fixed. It will pass in CI.

**Comment by monkeyDluffy6017** [comment]
The ci still failed

**Comment by SilentEntity** [comment]
Hi @monkeyDluffy6017, please check now

**Comment by SilentEntity** [comment]
The [libguice-java_4.2.1-1ubuntu0.1_all.deb](http://security.ubuntu.com/ubuntu/pool/universe/g/guice/libguice-java_4.2.1-1ubuntu0.1_all.deb) package is updated to [libguice-java_4.2.1-1ubuntu0.2_all.deb](http://security.ubuntu.com/ubuntu/pool/universe/g/guice/libguice-java_4.2.1-1ubuntu0.2_all.deb) on 2024-01-08 17:14.

The old package has been removed for the artifactory. For More info please see: http://security.ubuntu.com/ubuntu/pool/universe/g/guice/ .

Adding `apt-get update` before installing maven will fix the issue.

File to be changed: [.github/workflows/redhat-ci.yaml](https://github.com/apache/apisix/blob/master/.github/workflows/redhat-ci.yaml#L98)

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by AlinsRan — APPROVED** [review]
