### PR TITLE
fix: embedded UI redirect error when behind proxy

### LINKED ISSUE #12511: help request: Admin ui Redirected
### Issue description

I am using Docker image version 3.13.0. When I access the Admin UI through a reverse proxy, it redirects to IP:9180/ui. Due to some network policies, this address is not accessible. How can I handle this?

### Expected behavior

The page can be accessed normally when I use Nginx as a reverse proxy.

### How to Reproduce

1. use nginx proxy
2. access nginx_ip:port/ui

### Screenshots

_No response_

### Environment

- apisix version (cmd: `apisix version`): 3.13.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feranwq**
### Description

add absolute_redirect off; in /ui location to fix redirect port err

#### Which issue(s) this PR fixes:

Fixes #12511 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by Baoyuantop — DISMISSED** [review]

**Comment by juzhiyuan** [comment]
Hi I notice there are some failing tests

**Comment by feranwq** [comment]
> Hi I notice there are some failing tests

I've reviewed the error and it doesn't appear to be related to my PR. However, I can't be certain whether the err with the pre-existing code or the test itself.

File: apisix/cli/ngx_tpl.lua [hunk 1]
```diff
@@ -651,6 +651,7 @@ http {
 
         {% if enable_admin_ui then %}
         location = /ui {
+            absolute_redirect off;
```
Comment (bzp2010) [inline apisix/cli/ngx_tpl.lua:658]: Please add comments to explain why this directive is needed and how it works.

This is mainly to make a record to prevent future developers from accidentally removing or damaging it.

**Comment by SkyeYoung** [comment]
I reran the tests. Also, I agree with @bzp2010 's opinion.

**Comment by bzp2010** [comment]
Please do not force push after the review has begun; this wastes our time. 🤨

I believe the PR description already clearly explains this matter. If you do not believe this PR is ready for review, please place it in draft status until you have completed it and marked it as ready to review.

**Comment by feranwq** [comment]
> Please do not force push after the review has begun; this wastes our time. 🤨
> 
> I believe the PR description already clearly explains this matter. If you do not believe this PR is ready for review, please place it in draft status until you have completed it and marked it as ready to review.

Sorry, I'm used to using rebase to keep the commit history clean. I'll be mindful of this for any future modifications.

**Review by bzp2010 — APPROVED** [review]
This project always merges PRs using squash merges, so the commit history isn't very important.

**Review by Baoyuantop — APPROVED** [review]

**Comment by Baoyuantop** [comment]
Hi @feranwq, there's a failed test that needs to be resolved. I haven't identified the specific cause of the issue. Maybe you could merge the master branch and try again?

**Comment by feranwq** [comment]
> Hi @feranwq, there's a failed test that needs to be resolved. I haven't identified the specific cause of the issue. Maybe you could merge the master branch and try again?

It failed again, this time it was an mcp test failure. I've seen similar failures frequently in other pr, please help take a look.

**Comment by SkyeYoung** [comment]
@feranwq The test for this mcp-bridge often fails. I've rerun it for you.
