### PR TITLE
fix: remove conf server

### LINKED ISSUE #9381: help request: Error "lua_ssl_trusted_certificate" directive is duplicate in /usr/local/apisix/conf/nginx.conf:240
### Description

Hello. 
I am trying to install APICIS via Helm chart. At the same time, I need to link the control plane and etcd via mtls. 
I have separately installed an etcd cluster of three nodes.  Configured values for the control plane and mtls. And deploy Helm.
But in APISIX, when deploying, I get the error /usr/local/openresty//luajit/bin/luajit ./apisix/cli/api sys.lua init_etcd
2023/04/27 11:05:55 [emerg] 1#1: the directive "lua_ssl_trusted_certificate" is duplicated in /usr/local/apisix/conf/nginx.conf:240
nginx: [emerg] the directive "lua_ssl_trusted_certificate" is duplicated in /usr/local/apisix/conf/nginx.conf:240

Please, help me with this problem?

### Environment

- APISIX version (run `apisix version`): 3.2.0-debian
- Operating system (run `uname -a`): K8s 1.22, node OS is debian
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):  bitnami/etcd 3.5.7-debian-11-r14
- APISIX Dashboard version, if relevant: Not dashboard
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by kingluo**
### Description

https://lists.apache.org/thread/b69vjkbdszdtk9y30k45c2tvg4f3hqwt

Fixes #9381, #8067, #9212, #9049, #9582, #9578

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: t/chaos/killetcd/killetcd.go [hunk 1]
```diff
@@ -140,17 +140,12 @@ var _ = ginkgo.Describe("Test Get Success When Etcd Got Killed", func() {
...
 	ginkgo.It("get stats after kill etcd", func() {
-		timeStart := time.Now()
 		utils.SetRoute(e, httpexpect.Status5xx)
 		utils.GetRoute(eDataPanel, http.StatusOK)
 		utils.TestPrometheusEtcdMetric(ePrometheus, 0)
 
 		bandwidthAfter, durationAfter = utils.GetEgressBandwidthPerSecond(ePrometheus)
 		bpsAfter = bandwidthAfter / durationAfter
-
-		errorLog, err := utils.Log(apisixPod, cliSet.KubeCli, timeStart)
```
Comment (kingluo) [inline t/chaos/killetcd/killetcd.go:151]: Skip this test because it fails because it's a conf server specific test.
Note that we must keep this test even if we do not execute it, because it shares some data with the next test.

```
Error: 023/08/19 08:19:53 [error] 46#46: *9103 [lua] exporter.lua:456: handler(): prometheus: failed to reach config server while processing metrics endpoint: has no healthy etcd endpoint available
```

File: t/cli/test_access_log.sh [hunk 2]
```diff
@@ -91,12 +91,6 @@ if [ $count_test_access_log -eq 1 ]; then
     exit 1
 fi
 
-count_access_log_off=`grep -c "access_log off;" conf/nginx.conf || true`
```
Comment (kingluo) [inline t/cli/test_access_log.sh:94]: no access log for conf server anymore.

File: t/cli/test_deployment_control_plane.sh [hunk 3]
```diff
@@ -19,57 +19,6 @@
 
 . ./t/cli/common.sh
 
-echo '
```
Comment (kingluo) [inline t/cli/test_deployment_control_plane.sh:22]: remove useless schema tests

File: t/cli/test_deployment_control_plane.sh [hunk 4]
```diff
@@ -103,40 +45,6 @@ fi
 
 echo "passed: control_plane should enable Admin API"
 
-# use https
```
Comment (kingluo) [inline t/cli/test_deployment_control_plane.sh:106]: no https between cp and conf server anymore

File: t/cli/test_deployment_traditional.sh [hunk 5]
```diff
@@ -100,57 +100,6 @@ fi
 
 echo "passed: could connect to etcd"
 
-echo '
```
Comment (kingluo) [inline t/cli/test_deployment_traditional.sh:103]: only conf server requires all hosts to have the same scheme,

File: t/cli/test_deployment_traditional.sh [hunk 6]
```diff
@@ -100,57 +100,6 @@ fi
...
-if ! echo "$out" | grep 'all nodes in the etcd cluster should enable/disable TLS together'; then
-    echo "failed: should validate etcd host"
-    exit 1
-fi
-
-echo "passed: validate etcd host"
-
-# The 'admin.apisix.dev' is injected by ci/common.sh@set_coredns
-
-# etcd mTLS verify
```
Comment (kingluo) [inline t/cli/test_deployment_traditional.sh:125]: the mtls do not happen bewteen conf server and etcd anymore

File: t/cli/test_etcd_mtls.sh [hunk 7]
```diff
@@ -168,7 +168,7 @@ make run
 sleep 1
 make stop
 
-if ! grep -E 'upstream SSL certificate does not match \"127.0.0.1\" while SSL handshaking to upstream' logs/error.log; then
+if ! grep -F 'certificate host mismatch' logs/error.log; then
```
Comment (kingluo) [inline t/cli/test_etcd_mtls.sh:171]: Now https happens between lua-resty-http and etcd, and the log changes.

File: t/core/config_etcd.t [hunk 8]
```diff
@@ -84,9 +84,9 @@ end
 --- request
 GET /t
 --- grep_error_log chop
-peer closed connection in SSL handshake while SSL handshaking to upstream
+peer closed connection in SSL handshake
 --- grep_error_log_out eval
-qr/(peer closed connection in SSL handshake while SSL handshaking to upstream){1,}/
```
Comment (kingluo) [inline t/core/config_etcd.t:89]: Now https happens between lua-resty-http and etcd, and the log changes.

File: t/core/config_etcd.t [hunk 9]
```diff
@@ -118,42 +118,7 @@ qr/(closed){1,}/
 
 
 
-=== TEST 4: originate TLS connection to etcd cluster and verify TLS certificate (default behavior)
```
Comment (kingluo) [inline t/core/config_etcd.t:121]: Now we should make a CA bundle into the https://github.com/openresty/lua-nginx-module#lua_ssl_trusted_certificate directive in "/" location, instead of the conf server one.

**Review by leslie-tsang — APPROVED** [review]

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by leslie-tsang — APPROVED** [review]

**Review by monkeyDluffy6017 — APPROVED** [review]
