### PR TITLE
fix(traffic-split): binding upstream via upstream_id is invalid

### LINKED ISSUE #3740: bug: the traffic-split plugin is invalid to bind upstream via upstream_id
### Issue description

When both the routing and traffic-split plugins use upstream_id to bind upstream, the request distribution is not accurate.

1、add route and bind plugin

The upstream_id is 1, the response data is 1980, and the upstream_id is 2 the response data is 1981.

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "create_time":1614743731,
    "update_time":1614745342,
    "uris":[
        "/*"
    ],
    "name":"luarocks_cn",
    "methods":[
        "GET",
        "HEAD",
        "POST",
        "PUT",
        "DELETE",
        "OPTIONS",
        "PATCH"
    ],   
    "vars":[

    ],
    "plugins":{
        "proxy-rewrite":{
            "disable":false,
            "scheme":"http"
        },
        "traffic-split":{
            "disable":false,
            "rules":[
                {
                    "match":[
                        {
                            "vars":[
                                [
                                    "uri",
                                    "==",
                                    "/hello"
                                ]
                            ]
                        }
                    ],
                    "weighted_upstreams":[
                        {
                            "upstream_id":"2"
                        }
                    ]
                }
            ]
        }
    },
    "upstream_id":"1",
    "status":1
}
'
```

2、Test plugin

The vars rule passes:
```shell
$ curl http://127.0.0.1:9080/hello
1981
```

The vars rule failed：

```shell
$ curl http://127.0.0.1:9080/hello12
1980
```

The vars rule passes:
```shell
$ curl http://127.0.0.1:9080/hello
1981
```

The vars rule failed (an exception occurred)：

```shell
$ curl http://127.0.0.1:9080/hello12
1981
```

### PR DESCRIPTION
**Pull request by Firstsawyou**
### What this PR does / why we need it:

fix #3740
Related issues: #3787 

Because the current traffic-split plug-in supports `upstream_id` to refer to the upstream by rewriting the value of `ctx.matched_route.value.upstream_id`. However, when the upstream_id is used by the route and the plugin at the same time, the rewriting of `ctx` will cause the `upstream_id` on the original cached route to be lost.
Therefore, this PR creates a temporary variable of `ctx.upstream_id` to cache the upstream_id configured in the plug-in, avoiding the modification of `ctx.matched_route.value.upstream_id`.

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

File: apisix/init.lua [hunk 1]
```diff
@@ -387,6 +387,13 @@ function _M.http_access_phase()
     end
 
     local up_id = route.value.upstream_id
+
+    -- used for the traffic-split plugin
+    if route.value.upstream_id_tmp then
```
Comment (spacewander) [inline apisix/init.lua:392]: Maybe we can set & use `ctx.upstream_id` directly. No more modification to the route.

**Review by spacewander — CHANGES_REQUESTED** [review]

File: apisix/init.lua (hunk 1 above)
Comment (Firstsawyou) [reply apisix/init.lua:392]: Do you mean to directly set the variable of `ctx.upstream_id` in the traffic-split plugin to cache the upstream_id in the plugin?

Comment (spacewander) [reply apisix/init.lua:392]: Instead of setting `ctx.matched_route.value.upstream_id_tmp`, can we set `ctx.upstream_id` directly?

Comment (Firstsawyou) [reply apisix/init.lua:392]: This can directly set `ctx.upstream_id`, I will update the code.

Comment (Firstsawyou) [reply apisix/init.lua]: updated.

File: apisix/init.lua [hunk 2]
```diff
@@ -387,6 +387,13 @@ function _M.http_access_phase()
     end
 
     local up_id = route.value.upstream_id
+
+    -- used for the traffic-split plugin
+    if api_ctx.upstream_id then
+        up_id = api_ctx.upstream_id
+        api_ctx.upstream_id = nil
```
Comment (spacewander) [inline apisix/init.lua:394]: We don't need to remove it?

Comment (Firstsawyou) [reply apisix/init.lua:394]: Yes, we can choose not to delete it.

Comment (Firstsawyou) [reply apisix/init.lua]: updated.

**Review by spacewander — APPROVED** [review]

**Review by tokers — APPROVED** [review]
