### PR TITLE
fix: request failure during reload after any Eureka node fails

### LINKED ISSUE #12610: bug: dynamic upstream, one Eureka node is unavailable, half of the requests are lost after reloading
### Current Behavior

为了实现动态upstream, 配置了两个eureka的ip地址
Image

限制了一个eureka节点的访问, 持续请求无问题
Image

如果重载了apisix,就会出现一半请求失败,稳定复现
Image

discovery:
  eureka:
    host:
      - "http://10.250.200.99:8761"
      - "http://10.250.200.98:8761"
    prefix: "/eureka/"
    fetch_interval: 30               # 30s
    weight: 100                      # default weight for node
    timeout:
      connect: 2000                  # 2000ms
      send: 2000                     # 2000ms
      read: 5000                     # 5000ms

看起来受这个参数影响,如果设置抓取时间很短, 重载apisix后,会较快恢复
fetch_interval: 30

即使重载后,很短暂的几秒请求丢失, 对于nginx这种最重要的流量入口,也是不可接受的,所以希望能优化一下: 

重载或重启时候,一个节点可以连接,一个节点不可用连接,因为两个eureka节点数据一致, 就可以拿到全量动态upstream的服务列表, 不能因为一个eureka节点连接不上,就导致请求一半失败!

### Expected Behavior

_No response_

### Error Logs

_No response_

### Steps to Reproduce

1.apisix配置注册中心eureka,两个节点
discovery:
  eureka:
    host:
      - "http://10.250.200.99:8761"
      - "http://10.250.200.98:8761"
    prefix: "/eureka/"
    fetch_interval: 3               # 30s
    weight: 100                      # default weight for node
    timeout:
      connect: 2000                  # 2000ms
      send: 2000                     # 2000ms
      read: 2000                     # 5000ms

2.在一个eureka节点主机上禁用掉apisix的ip所有请求
iptables -A INPUT -s 10.250.200.202 -j DROP

3.持续curl请求,正常

4.systemctl reload apisix

5.持续curl请求,请求有一半失败

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by SkyeYoung**
## Summary
Fix eureka service discovery to retry all configured endpoints when one fails, preventing 503 errors on APISIX restart when some eureka services are unhealthy.

## Problem
When APISIX restarts with multiple eureka services configured (some healthy, some unhealthy), each worker randomly selects one eureka node. Workers that hit an unhealthy node fail silently, leaving their `applications` variable as `nil`, causing 503 errors for requests routed to those workers.

## Changes
- **Add `build_endpoints()` function** - Converts all eureka hosts from config to endpoint objects with URL and auth info, handling prefix and trailing slash normalization.

- **Implement endpoint failover in `fetch_full_registry()`** - Start from a random endpoint position for load balancing, then try endpoints sequentially until one succeeds. If all fail, log error and return without clearing existing applications data.

- **Add test case** - Added TEST 4 in `t/discovery/eureka.t` to verify failover behavior when first eureka host returns 502.

#### refs

https://github.com/apache/apisix/pull/12734

#### Which issue(s) this PR fixes:

Fixes #12610

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/discovery/eureka/init.lua [hunk 1]
```diff
@@ -210,6 +225,7 @@ function _M.init_worker()
     log.info("default_weight:", default_weight, ".")
     local fetch_interval = local_conf.discovery.eureka.fetch_interval or 30
     log.info("fetch_interval:", fetch_interval, ".")
+
```
Comment (SkyeYoung) [inline apisix/discovery/eureka/init.lua]:
```suggestion
```

File: apisix/discovery/eureka/init.lua [hunk 2]
```diff
@@ -140,31 +109,75 @@ local function parse_instance(instance)
...
+    local num_endpoints = #endpoints
+    local start = math_random(num_endpoints)
+    for i = 0, num_endpoints - 1 do
+        local endpoint = endpoints[(start + i - 1) % num_endpoints + 1]
+        local r, e = request(endpoint.url, endpoint.auth, "GET", "apps")
+        if r and r.body and r.status == 200 then
+            selected_endpoint = endpoint
+            selected_body = r.body
+            break
+        end
```
Comment (bzp2010) [inline apisix/discovery/eureka/init.lua:168]: This modification essentially ensures that if a registry unexpectedly fails, it will retry until a good registry is used. While this may introduce some additional latency, is it necessary to document it?

Comment (SkyeYoung) [reply apisix/discovery/eureka/init.lua:168]: Perhaps we should add a similar description to all service discovery documentation.

File: apisix/discovery/eureka/init.lua [hunk 3]
```diff
@@ -39,34 +39,37 @@ local _M = {
...
-    end
-    if local_conf.discovery.eureka.prefix then
-        url = url .. local_conf.discovery.eureka.prefix
-    end
-    if string_sub(url, #url) ~= "/" then
-        url = url .. "/"
+        return nil
+    end
+
+    local built_endpoints = core.table.new(#host_list, 0)
```
Comment (moonming) [inline apisix/discovery/eureka/init.lua:51]: we can cache this table instead of create a new one for every request.

File: apisix/discovery/eureka/init.lua [hunk 4]
```diff
@@ -145,26 +148,36 @@ local function fetch_full_registry(premature)
...
+    local start = math_random(num_endpoints)
+    for i = 0, num_endpoints - 1 do
+        local endpoint = endpoints[(start + i - 1) % num_endpoints + 1]
+        local r, e = request(endpoint.url, endpoint.auth, "GET", "apps")
+        if r and r.body and r.status == 200 then
+            selected_endpoint = endpoint
+            selected_body = r.body
+            break
+        end
+        log.warn("failed to fetch registry from ", endpoint.url, ": ",
```
Comment (membphis) [inline apisix/discovery/eureka/init.lua]: should use error log level

File: apisix/discovery/eureka/init.lua [hunk 5]
```diff
@@ -145,26 +148,36 @@ local function fetch_full_registry(premature)
...
-    if not res then
-        log.error("failed to fetch registry", err)
-        return
+    -- try endpoints from random position, failover on error
+    local selected_endpoint
+    local selected_body
+    local num_endpoints = #endpoints
+    local start = math_random(num_endpoints)
+    for i = 0, num_endpoints - 1 do
+        local endpoint = endpoints[(start + i - 1) % num_endpoints + 1]
```
Comment (membphis) [inline apisix/discovery/eureka/init.lua:162]:
```suggestion
        local endpoint = endpoints[(start + i) % num_endpoints]
```

Comment (SkyeYoung) [reply apisix/discovery/eureka/init.lua:162]: num_endpoints = 3，start = 1

i | (start + i - 1) % 3 + 1 | (start + i) % 3
-- | -- | --
0 | (1 + 0 - 1) % 3 + 1 = 1 | (1 + 0) % 3 = 1
1 | (1 + 1 - 1) % 3 + 1 = 2 | (1 + 1) % 3 = 2
2 | (1 + 2 - 1) % 3 + 1 = 3 | (1 + 2) % 3 = 0

Comment (SkyeYoung) [reply apisix/discovery/eureka/init.lua:162]: Is the list not `1-based`?

File: apisix/discovery/eureka/init.lua (hunk 4 above)
Comment (SkyeYoung) [reply apisix/discovery/eureka/init.lua]: done

File: apisix/discovery/eureka/init.lua (hunk 5 above)
Comment (membphis) [reply apisix/discovery/eureka/init.lua:162]: your way right, nine

File: apisix/discovery/eureka/init.lua (hunk 3 above)
Comment (SkyeYoung) [reply apisix/discovery/eureka/init.lua:51]: The current calling relationship is as follows:

fetch_full_registry -> build_endpoints

```lua
function _M.init_worker()
    ...
    ngx_timer_at(0, fetch_full_registry)
    ngx_timer_every(fetch_interval, fetch_full_registry)
end
```

File: apisix/discovery/eureka/init.lua [hunk 6]
```diff
@@ -145,26 +148,36 @@ local function fetch_full_registry(premature)
...
+            break
+        end
+        log.error("failed to fetch registry from ", endpoint.url, ": ",
+                 e or (r and ("status=" .. tostring(r.status)) or "unknown"))
     end
 
-    if not res.body or res.status ~= 200 then
-        log.error("failed to fetch registry, status = ", res.status)
+    if not selected_endpoint then
+        log.error("failed to fetch registry from all eureka hosts")
```
Comment (membphis) [inline apisix/discovery/eureka/init.lua]: need more information, eg: no healthy registry, the count of all hosts

Comment (SkyeYoung) [reply apisix/discovery/eureka/init.lua]: ok.

**Review by membphis — APPROVED** [review]
