### PR TITLE
fix: APISIX runs in the `/root` directory and reports errors

### LINKED ISSUE #3207: apisix-2.1/apisix/init.lua:89: module 'resty.worker.events' not found:
1. 报错详情：
```
[error] 6302#6302: init_worker_by_lua error: /root/apisix-2.1/apisix/init.lua:89: module 'resty.worker.events' not found:
        no field package.preload['resty.worker.events']
        no file '/root/apisix-2.1//deps/share/lua/5.1/resty/worker/events.lua'
        no file '/root/apisix-2.1//deps/share/lua/5.1/resty/worker/events/init.lua'
        no file '/root/apisix-2.1/resty/worker/events.lua'
        no file '/root/apisix-2.1/resty/worker/events/init.lua'
        no file '/usr/local/openresty/site/lualib/resty/worker/events.ljbc'
        no file '/usr/local/openresty/site/lualib/resty/worker/events/init.ljbc'
        no file '/usr/local/openresty/lualib/resty/worker/events.ljbc'
        no file '/usr/local/openresty/lualib/resty/worker/events/init.ljbc'
        no file '/usr/local/openresty/site/lualib/resty/worker/events.lua'
        no file '/usr/local/openresty/site/lualib/resty/worker/events/init.lua'
        no file '/usr/local/openresty/lualib/resty/worker/events.lua'
        no file '/usr/local/openresty/lualib/resty/worker/events/init.lua'
        no file './resty/worker/events.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
        no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
        no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
        no file './resty/worker/events.lua'
        no file '/usr/share/lua/5.1/resty/worker/events.lua'
        no file '/usr/share/lua/5.1/resty/worker/events/init.lua'
        no file '/usr/lib64/lua/5.1/resty/worker/events.lua'
        no file '/usr/lib64/lua/5.1/resty/worker/events/init.lua'
        no file '/root/apisix-2.1//deps/lib64/lua/5.1/resty/worker/events.so'
        no file '/root/apisix-2.1//deps/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/openresty/site/lualib/resty/worker/events.so'
        no file '/usr/local/openresty/lualib/resty/worker/events.so'
        no file './resty/worker/events.so'
        no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty/worker/events.so'
        no file '/usr/lib64/lua/5.1/resty/worker/events.so'
        no file '/usr/lib64/lua/5.1/loadall.so'
        no file '/root/apisix-2.1//deps/lib64/lua/5.1/resty.so'
        no file '/root/apisix-2.1//deps/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/site/lualib/resty.so'
        no file '/usr/local/openresty/lualib/resty.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/lib64/lua/5.1/resty.so'
        no file '/usr/lib64/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /root/apisix-2.1/apisix/init.lua:89: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk
```

2. 安装步骤：

- 安装依赖

```
# 安装 epel, `luarocks` 需要它
wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo rpm -ivh epel-release-latest-7.noarch.rpm

# 安装 etcd
wget https://github.com/etcd-io/etcd/releases/download/v3.4.13/etcd-v3.4.13-linux-amd64.tar.gz
tar -xvf etcd-v3.4.13-linux-amd64.tar.gz && \
    cd etcd-v3.4.13-linux-amd64 && \
    sudo cp -a etcd etcdctl /usr/bin/

# 添加 OpenResty 源
sudo yum install yum-utils
sudo yum-config-manager --add-repo https://openresty.org/package/centos/openresty.repo

# 安装 OpenResty 和 编译工具
sudo yum install -y openresty curl git gcc luarocks lua-devel

# 开启 etcd server
nohup etcd &

```

- 通过源码包安装
```
mkdir apisix-2.1
wget https://downloads.apache.org/apisix/2.1/apache-apisix-2.1-src.tgz
tar zxvf apache-apisix-2.1-src.tgz -C apisix-2.1
```

- 安装运行时依赖的 Lua 库
```
cd apisix-2.1
make deps
```
- 管理（启动、关闭等）APISIX 服务
```
# init nginx config file and etcd
$ make init

# start APISIX server
$ make run

# stop APISIX server
$ make stop
```

### PR DESCRIPTION
**Pull request by Firstsawyou**
### What this PR does / why we need it:

Cause of the bug: After APISIX is started, the `worker process` has the authority of nobody ordinary user. When APISIX is in the /root directory, ordinary users do not have the authority to access the `/root` directory. Therefore, when APISIX is started, the error log `error.log` will show the following error message:

```
init_worker_by_lua error: /root/apisix-2.1/apisix/init.lua:89: module 'resty.worker.events' not found:
        no field package.preload['resty.worker.events']
        no file '/root/apisix-2.1//deps/share/lua/5.1/resty/worker/events.lua'
        no file '/root/apisix-2.1//deps/share/lua/5.1/resty/worker/events/init.lua'
        no file '/root/apisix-2.1/resty/worker/events.lua'
        no file '/root/apisix-2.1/resty/worker/events/init.lua'
```

The solution: it is forbidden to execute make run in the /root directory to run apisix.

close #3207
### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -83,7 +83,9 @@ init: default
 ### run:              Start the apisix server
 .PHONY: run
 run: default
-ifeq ("$(wildcard logs/nginx.pid)", "")
+ifeq ("$(findstring /root, ${PWD})", "/root")
+	@echo "Warning! It is forbidden to run APISIX in the /root directory."
```
Comment (spacewander) [inline Makefile:87]: It should be an error and exit with nonzero code, as APISIX won't be run.

Comment (Firstsawyou) [reply Makefile]: updated.

File: Makefile [hunk 2]
```diff
@@ -83,7 +83,10 @@ init: default
 ### run:              Start the apisix server
 .PHONY: run
 run: default
-ifeq ("$(wildcard logs/nginx.pid)", "")
+ifeq ("$(findstring /root, ${PWD})", "/root")
+	@echo "Non-zero exit status: 1"
```
Comment (spacewander) [inline Makefile:87]: I mean to exit the Makefile with non-zero exit code.

Comment (Firstsawyou) [reply Makefile]: @spacewander 
Updated, please help me to see, is this right?

File: Makefile [hunk 3]
```diff
@@ -84,8 +84,8 @@ init: default
 .PHONY: run
 run: default
 ifeq ("$(findstring /root, ${PWD})", "/root")
-	@echo "Non-zero exit status: 1"
-	@echo "Error, It is forbidden to run APISIX in the /root directory."
+	@echo "Error: It is forbidden to run APISIX in the /root directory."
+	@exit 1
```
Comment (spacewander) [inline Makefile:88]: We need to add a test for it.

Comment (Firstsawyou) [reply Makefile:88]: I don't know how to add test cases for Makefile. Can you give me some suggestions?

Comment (spacewander) [reply Makefile:88]: See https://github.com/apache/apisix/blob/ebd158a8583306183533e92cb87d39854b0af42a/.travis/apisix_cli_test/test_main.sh#L920

Comment (Firstsawyou) [reply Makefile:88]: 好的，我知道了。

**Comment by moonming** [comment]
I don't think this method can completely solve the permission problem.  Can an error be thrown if the code file cannot be found in the init phase of apisix?

**Comment by Firstsawyou** [comment]
> I don't think this method can completely solve the permission problem. Can an error be thrown if the code file cannot be found in the init phase of apisix?

There will be no errors when executing `make init`. Only when `make run` is executed, it will cause an error that dependent files cannot be found. Therefore, I think prohibiting the execution of `make run` under `/root` can solve this problem.

File: Makefile [hunk 4]
```diff
@@ -83,7 +83,10 @@ init: default
 ### run:              Start the apisix server
 .PHONY: run
 run: default
-ifeq ("$(wildcard logs/nginx.pid)", "")
+ifeq ("$(findstring /root, ${PWD})", "/root")
```
Comment (moonming) [inline Makefile:86]: We need a thorough solution, not a temporary patch

**Review by moonming — CHANGES_REQUESTED** [review]

File: Makefile (hunk 4 above)
Comment (Firstsawyou) [reply Makefile:86]: Ok, got it.

Comment (Firstsawyou) [reply Makefile]: updated.

File: apisix/cli/ops.lua [hunk 5]
```diff
@@ -375,6 +375,10 @@ end
 
 
 local function start(env, ...)
+    if env.is_root_path then
+        util.die("Error: It is forbidden to run APISIX in the /root directory.\n")
```
Comment (moonming) [inline apisix/cli/ops.lua:379]: I think you don’t understand the permissions issues under Linux at all

**Review by moonming — CHANGES_REQUESTED** [review]

File: t/cli/cli.t [hunk 6]
```diff
@@ -58,3 +58,21 @@ nameserver 172.27.0.1
 nameserver fe80::215:5dff:fec5:8e1d
 --- response_body
 ["172.27.0.1","fe80::215:5dff:fec5:8e1d"]
+
+
+
+=== TEST 2: It is forbidden to run APISIX under the /root directory(is_root_path is true).
```
Comment (membphis) [inline t/cli/cli.t:64]: we should use `shell` script to test this case

File: apisix/cli/ops.lua (hunk 5 above)
Comment (membphis) [reply apisix/cli/ops.lua:379]: the current way is right, but it is hard to read. @Firstsawyou please add some comment here.

image

**Review by membphis — CHANGES_REQUESTED** [review]

File: t/cli/cli.t (hunk 6 above)
Comment (Firstsawyou) [reply t/cli/cli.t]: updated.

**Comment by membphis** [comment]
@Firstsawyou CI failed, please fix it first

**Comment by Firstsawyou** [comment]
> @Firstsawyou CI failed, please fix it first

Okay, I will fix it later.

File: apisix/cli/ops.lua (hunk 5 above)
Comment (membphis) [reply apisix/cli/ops.lua:379]: any news? @Firstsawyou

**Review by membphis — CHANGES_REQUESTED** [review]

File: apisix/cli/ops.lua (hunk 5 above)
Comment (Firstsawyou) [reply apisix/cli/ops.lua:379]: A note has been added here: [https://github.com/apache/apisix/pull/3220/files#diff-c25d1a2aac172147aa01feec3fa29bfe6c4625cda4773719a1cf13e67fd54da2R42 ](https://github.com/apache/apisix/pull/3220/files#diff-c25d1a2aac172147aa01feec3fa29bfe6c4625cda4773719a1cf13e67fd54da2R42)

I will add more comments here later:
https://github.com/apache/apisix/pull/3220/files#diff-228a51571b53709ad043d1c6c14fc8e508c248a84f8014fe548b5d259cedd5ddR378

Comment (Firstsawyou) [reply apisix/cli/ops.lua:379]: Cause of the bug: After APISIX is started, the `worker process` has the authority of nobody ordinary user. When APISIX is in the /root directory, ordinary users do not have the authority to access the `/root` directory. Therefore, when APISIX is started, the error log `error.log` will show the following error message:

```
init_worker_by_lua error: /root/apisix-2.1/apisix/init.lua:89: module 'resty.worker.events' not found:
        no field package.preload['resty.worker.events']
        no file '/root/apisix-2.1//deps/share/lua/5.1/resty/worker/events.lua'
        no file '/root/apisix-2.1//deps/share/lua/5.1/resty/worker/events/init.lua'
        no file '/root/apisix-2.1/resty/worker/events.lua'
        no file '/root/apisix-2.1/resty/worker/events/init.lua'
```

Comment (Firstsawyou) [reply apisix/cli/ops.lua:382]: > any news? @Firstsawyou

updated.

**Review by spacewander — APPROVED** [review]

**Review by membphis — APPROVED** [review]

**Comment by membphis** [comment]
ping @moonming

**Review by moonming — APPROVED** [review]

**Comment by ccxhwmy** [comment]
I think this only solves the permission problem of apisix deployed under `/root`, if I deploy it under `/home/work1` and I use work2 as user, the problem still exists.

**Comment by tzssangglass** [comment]
> I think this only solves the permission problem of apisix deployed under `/root`, if I deploy it under `/home/work1` and I use work2 as user, the problem still exists.

Obviously, this PR solves the problem that APISIX runs under `/root`.

Please submit a new issue describing your problem.
