### PR TITLE
fix(standalone): API-driven mode does not properly handle consumer schema

### LINKED ISSUE #12253: bug: API-driven standalone mode does not properly handle consumer schema checks
### Current Behavior

The `consumers` does not support inputs that contain a `modifiedIndex` field.

The `core.config.new(“/consumers”, cfg)` does not include an `item_schema` input similar to the other resources because consumers needs to handle both consumer and consumer_credential resources under the same key.
It just passes in a function that checks the schema and determines the resource type by key and performs specific checks if needed.
The additional field `modifiedIndex` that we have now introduced in config_yaml cannot be applied to the internal check function of consumers, so the check will output an error.

### Expected Behavior

Consistent with other resources.

### Error Logs

```text
invalid consumers at index 0, err: additional properties forbidden, found modifiedIndex
```

### Steps to Reproduce

1. Use the API to submit a consumer containing the `modifiedIndex`.

### Environment

- APISIX version (run `apisix version`): master
- Operating system (run `uname -a`): N/A
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): N/A
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): N/A
- APISIX Dashboard version, if relevant: N/A
- Plugin runner version, for issues related to plugin runners: N/A
- LuaRocks version, for installation issues (run `luarocks --version`): N/A

### PR DESCRIPTION
**Pull request by AlinsRan**
#### Which issue(s) this PR fixes:

Fixes #12253 

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/core/config_yaml.lua [hunk 1]
```diff
@@ -274,7 +275,7 @@ local function sync_data(self)
                           ", it should be an object")
             end
 
-            local id = item.id or ("arr_" .. idx)
+            local id = item.id or item.username or ("arr_" .. idx)
```
Comment (nic-6443) [inline apisix/core/config_yaml.lua:278]: Is this change necessary? We have already set `id` to `username` for consumer in `apisix/consumer.lua`.
```
consumer.value.id = consumer.value.username
```

Comment (AlinsRan) [reply apisix/core/config_yaml.lua:278]: If not, the default is values_hash ["arr_1"] = consumer{}, 

The filter is called after the cache is set. In the following calls, it will not get the consumer


image


image

**Review by nic-6443 — DISMISSED** [review]

File: apisix/schema_def.lua [hunk 2]
```diff
@@ -729,7 +729,18 @@ _M.credential = {
...
+            oneOf = {
+                id_schema,
+                -- id: "${consumer_name}/credentials/${credential_id}" from standalone mode
+                {
+                    type = "string",
+                    minLength = 15,
+                    maxLength = 128,
+                    pattern = [[^[a-zA-Z0-9]+/credentials/[a-zA-Z0-9]+$]],
+                }
+            }
```
Comment (bzp2010) [inline apisix/schema_def.lua:742]: If this is standalone-specific, it should be overridden when standalone is enabled, rather than using oneOf.
oneOf is ambiguous at some point and is not conducive to various downstream components using its type.

File: apisix/admin/standalone.lua [hunk 3]
```diff
@@ -235,6 +240,36 @@ function _M.run()
 end
 
 
+local schema_patch
+do
+    local resource_schema = {
```
[the remark this answers is not in the document]
Comment (AlinsRan) [reply apisix/admin/standalone.lua:245]: I don't think it's necessary, `plugin_metadata` is not defined in schema_def, and its structure depends on plugin customization.

[the remark this answers is not in the document]
Comment (bzp2010) [reply apisix/admin/standalone.lua:245]: So the `modifiedIndex` on `plugin_metadata` actually benefits from the fact that the plugin itself doesn't declare `additionalProperties`, which doesn't prevent the plugin from writing without recognizing the field. Right?

File: apisix/schema_def.lua (hunk 2 above)
Comment (bzp2010) [reply apisix/schema_def.lua]: Now, instead of modifying the schema after making a deep copy, this module just modifies it, which is as expected?

File: apisix/admin/standalone.lua (hunk 3 above)
[the remark this answers is not in the document]
Comment (AlinsRan) [reply apisix/admin/standalone.lua:245]: Yes.

**Review by bzp2010 — APPROVED** [review]
