### PR TITLE
fix: ctx being contaminated due to a new feature of openresty 1.19

### LINKED ISSUE #3079: apisix转发流量错误
### Issue description
apisix按照如下配置时，有一定几率会转发流量错误

### Environment

* apisix version (2.1):
* OS: centos7.8

## 描述
三个域名对应三个route，假定a b c,两个上游 ，假定 x  y，其中xy都只有一个节点，roundrobin,权重1，对应关系为 a->x       ,b   c   ->y,  在转发流量的过程中，当qps在>50之后，约有8%-15%的流量会转发错误，即a->y,b->x，经验证x，y获取到的所有header是客户正常发送的，apisix却分派错了

### upstreams：

```
"action":"get",
"node":{
"nodes":[
{
"createdIndex":2,
"modifiedIndex":2,
"key":"\/apisix\/upstreams\/333621554711626091",
"value":{
"nodes":[
{
"host":"172.16.27.9",
"port":8088,
"weight":1
}
],
"id":"333621554711626091",
"name":"ceshi-upstream",
"update_time":1608383542,
"type":"roundrobin",
"create_time":1608383542,
"timeout":{
"connect":6000,
"read":6000,
"send":6000
}
}
},
{
"createdIndex":3,
"modifiedIndex":3,
"key":"\/apisix\/upstreams\/333621685657796971",
"value":{
"nodes":[
{
"host":"172.16.27.2",
"port":8087,
"weight":1
}
],
"id":"333621685657796971",
"name":"dz11ht-upstream",
"update_time":1608383620,
"type":"roundrobin",
"create_time":1608383620,
"timeout":{
"connect":6000,
"read":6000,
"send":6000
}
}
},
{
"createdIndex":4,
"modifiedIndex":4,
"key":"\/apisix\/upstreams\/333621748001931627",
"value":{
"nodes":[
{
"host":"172.16.27.2",
"port":8086,
"weight":1
}
],
"id":"333621748001931627",
"name":"dz11-front-upstream",
"update_time":1608383657,
"type":"roundrobin",
"create_time":1608383657,
"timeout":{
"connect":6000,
"read":6000,
"send":6000
}
}
}
],
"dir":true,
"createdIndex":10,
"key":"\/apisix\/upstreams",
"modifiedIndex":76
},
"count":"4",
"header":{
"raft_term":"2",
"member_id":"10276657743932975437",
"revision":"86",
"cluster_id":"14841639068965178418"
}
}
```

### route

```
{
"action":"get",
"node":{
"nodes":[
{
"createdIndex":5,
"modifiedIndex":20,
"key":"\/apisix\/routes\/333621797343723883",
"value":{
"id":"333621797343723883",
"vars":{
},
"methods":[
"GET",
"HEAD",
"POST",
"PUT",
"DELETE",
"OPTIONS",
"PATCH"
],
"hosts":[
"ceshi.abc.com"
],
"uris":[
"\/*"
],
"update_time":1608384782,
"create_time":1608383687,
"upstream_id":"333621554711626091",
"name":"ceshi-route"
}
},
{
"createdIndex":6,
"modifiedIndex":6,
"key":"\/apisix\/routes\/333622024255570283",
"value":{
"id":"333622024255570283",
"vars":{
},
"methods":[
"GET",
"HEAD",
"POST",
"PUT",
"DELETE",
"OPTIONS",
"PATCH"
],
"hosts":[
"dz11ht.abc.com"
],
"uris":[
"\/*"
],
"update_time":1608383822,
"create_time":1608383822,
"upstream_id":"333621685657796971",
"name":"dz1-route"
}
},
{
"createdIndex":7,
"modifiedIndex":7,
"key":"\/apisix\/routes\/333622061215777131",
"value":{
"id":"333622061215777131",
"vars":{
},
"methods":[
"GET",
"HEAD",
"POST",
"PUT",
"DELETE",
"OPTIONS",
"PATCH"
],
"hosts":[
"dzhtabc.com"
],
"uris":[
"\/*"
],
"update_time":1608383844,
"create_time":1608383844,
"upstream_id":"333621685657796971",
"name":"httest-api-route"
}
},
{
"createdIndex":21,
"modifiedIndex":21,
"key":"\/apisix\/routes\/333623666443026795",
"value":{
"id":"333623666443026795",
"vars":{
},
"methods":[
"GET",
"HEAD",
"POST",
"PUT",
"DELETE",
"OPTIONS",
"PATCH"
],
"hosts":[
"test.abc.com"
],
"uris":[
"\/*"
],
"update_time":1608384801,
"create_time":1608384801,
"upstream_id":"333621554711626091",
"name":"test-api-route"
}
},
{
"createdIndex":34,
"modifiedIndex":35,
"key":"\/apisix\/routes\/333627619691987307",
"value":{
"id":"333627619691987307",
"vars":{
},
"methods":[
"GET",
"HEAD",
"POST",
"PUT",
"DELETE",
"OPTIONS",
"PATCH"
],
"hosts":[
"dz11.abccom"
],
"uris":[
"\/*"
],
"update_time":1608388794,
"create_time":1608387157,
"upstream_id":"333621748001931627",
"name":"dzfw-route"
}
}
],
"dir":true,
"createdIndex":9,
"key":"\/apisix\/routes",
"modifiedIndex":75
},
"count":"6",
"header":{
"raft_term":"2",
"member_id":"10276657743932975437",
"revision":"86",
"cluster_id":"14841639068965178418"
}
}
```

### PR DESCRIPTION
**Pull request by nic-chen**
### What this PR does / why we need it:

A new feature has been added in OpenResty 1.19.3.1:
`Shared ngx.ctx among SSL_* phases and the following phases.`

In the ssl phase, ctx is created but not cleared. 

In the access phase, it is judged that if ctx already exists, it will not be created. 

This causes a same client to access an `https` service and then access another `http` service, it will be reused the previous ctx, resulting in this bug.

fix #3079

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
       we could add test cases later for quick fix. we could track it by #3103  
* [ ] Have you modified the corresponding document?
       we don't need to modify docs for this change.
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by moonming — CHANGES_REQUESTED** [review]
I don't think this is a good title of PR, and we need test cases

**Comment by membphis** [comment]
related issue: https://github.com/apache/apisix/issues/3103

File: apisix/init.lua [hunk 1]
```diff
@@ -185,6 +185,7 @@ function _M.http_ssl_phase()
         end
         ngx_exit(-1)
     end
+    ngx.ctx = nil
```
Comment (membphis) [inline apisix/init.lua:188]: need comments

File: apisix/init.lua [hunk 2]
```diff
@@ -334,12 +335,8 @@ end
...
 function _M.http_access_phase()
     local ngx_ctx = ngx.ctx
-    local api_ctx = ngx_ctx.api_ctx
-
-    if not api_ctx then
-        api_ctx = core.tablepool.fetch("api_ctx", 0, 32)
-        ngx_ctx.api_ctx = api_ctx
-    end
+    local api_ctx = core.tablepool.fetch("api_ctx", 0, 32)
+    ngx_ctx.api_ctx = api_ctx
```
Comment (membphis) [inline apisix/init.lua:339]: ditto

**Review by membphis — CHANGES_REQUESTED** [review]

File: apisix/init.lua (hunk 1 above)
Comment (nic-chen) [reply apisix/init.lua:190]: fixed.

File: apisix/init.lua (hunk 2 above)
Comment (nic-chen) [reply apisix/init.lua:342]: fixed.

**Comment by nic-chen** [comment]
> I don't think this is a good title of PR, and we need test cases

@moonming 
we confirmed the changes in the user's env.
maybe we could add test cases later for quick fix. we could track it by #3103

File: apisix/init.lua [hunk 3]
```diff
@@ -185,6 +185,9 @@ function _M.http_ssl_phase()
         end
         ngx_exit(-1)
```
Comment (spacewander) [inline apisix/init.lua:186]: Should we also clear the `ngx.ctx` here?

**Review by membphis — APPROVED** [review]

**Review by tokers — APPROVED** [review]

File: apisix/init.lua (hunk 3 above)
Comment (membphis) [reply apisix/init.lua:186]: If the SSL handshake fails, there will be no more HTTP requests.

**Review by spacewander — APPROVED** [review]

File: apisix/init.lua (hunk 3 above)
Comment (spacewander) [reply apisix/init.lua:188]: @membphis 
You are right.

**Comment by membphis** [comment]
@nic-chen CI failed

**Review by moonming — APPROVED** [review]

**Comment by membphis** [comment]
@nic-chen please update your source code editor to avoid those issue: https://github.com/apache/apisix/pull/3105/commits/7f000047f74811cd4b8521139e6e51f5401b4a5d

**Comment by nic-chen** [comment]
> @nic-chen please update your source code editor to avoid those issue: [7f00004](https://github.com/apache/apisix/commit/7f000047f74811cd4b8521139e6e51f5401b4a5d)

OK
