### PR TITLE
fix: the query string is repeated twice when enable http-to-https and append-query-string (#7394)

### LINKED ISSUE #7394: bug: enable both `http_to_https` and `append_query_string` of the redirect plugin will cause the query string to be repeated twice
### Current Behavior

```
curl --location --request PUT 'http://apisix-admin:9180/apisix/admin/routes/redirect' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "host": "redirect",
    "uri": "/*",
    "upstream": {
        "type": "roundrobin",
        "nodes": [
            {
                "host": "httpbin",
                "port": 80,
                "weight": 1
            }
        ]
    },
    "plugins": {
        "redirect": {
            "http_to_https": true,
            "append_query_string": true
        }
    },
    "name": "redirect"
}'
```

```
❯ curl --noproxy '*' http://apisix-gateway/ip\?hello\=world -H "Host: redirect" -v
*   Trying 10.98.108.144:80...
* TCP_NODELAY set
* Connected to apisix-gateway (10.98.108.144) port 80 (#0)
> GET /ip?hello=world HTTP/1.1
> Host: redirect
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 06 Jul 2022 08:21:16 GMT
< Content-Type: text/html
< Content-Length: 166
< Connection: keep-alive
< Location: https://redirect/ip?hello=world&hello=world
< Server: APISIX/2.13.1
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
* Connection #0 to host apisix-gateway left intact

```

### Expected Behavior

Tell the user in the documentation not to use both `http_to_https` and `append_query_string` options, or that apisix automatically handles not repeating the query string when both options are configured at the same time

### Error Logs

_No response_

### Steps to Reproduce

/

### Environment

- APISIX version (run `apisix version`): 2.13.1

### PR DESCRIPTION
**Pull request by vyvyan2010**
### Description

Fix bug that the query string is repeated twice when enable http-to-https and append-query-string

Fixes #7394

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/plugins/redirect.lua [hunk 1]
```diff
@@ -55,13 +55,32 @@ local schema = {
         },
         http_to_https = {type = "boolean"},
         encode_uri = {type = "boolean", default = false},
-        append_query_string = {type = "boolean", default = false},
+        append_query_string = {type = "boolean"},
```
Comment (tokers) [inline apisix/plugins/redirect.lua:58]: Why change this line?

File: docs/en/latest/plugins/redirect.md [hunk 2]
```diff
@@ -34,7 +34,7 @@ The `redirect` Plugin can be used to configure redirects.
...
-| http_to_https       | boolean       | False    | false   |              | When set to `true` and the request is HTTP, it will be redirected to HTTPS with the same URI with a 301 status code.                                                                                                                                                                                                                                                               |
+| http_to_https       | boolean       | False    | false   |              | When set to `true` and the request is HTTP, it will be redirected to HTTPS with the same URI with a 301 status code, contains the query string.                                                                                                                                                                                                                                                               |
```
Comment (tokers) [inline docs/en/latest/plugins/redirect.md:37]:
```suggestion
| http_to_https       | boolean       | False    | false   |              | When set to `true` and the request is HTTP, it will be redirected to HTTPS with the same URI with a 301 status code.  Note the querystring from the raw URI will also be contained in the Location header.                                                                                                                                                                                                                                                             |
```

File: docs/en/latest/plugins/redirect.md [hunk 3]
```diff
@@ -44,6 +44,7 @@ The `redirect` Plugin can be used to configure redirects.
 :::note
 
 Only one of `http_to_https`, `uri` and `regex_uri` can be configured.
+Only one of `http_to_https` and `append_query_string` can be configured.
```
Comment (tokers) [inline docs/en/latest/plugins/redirect.md:47]:
```suggestion
* Only one of `http_to_https`, `uri` and `regex_uri` can be configured.
* Only one of `http_to_https` and `append_query_string` can be configured.
```

File: t/plugin/redirect.t [hunk 4]
```diff
@@ -582,13 +582,48 @@ Location: https://foo.com:9443/hello
...
 --- response_body eval
-qr/error_msg":"failed to check the configuration of plugin redirect err: value should match only one schema, but matches both schemas 1 and 3/
+qr/error_msg":"failed to check the configuration of plugin redirect err: allOf 1 failed: value should match only one schema, but matches both schemas 1 and 3/
 --- no_error_log
 [error]
 
 
 
-=== TEST 26: enable http_to_https with upstream
+=== TEST 26: wrong configure, enable http_to_https with append_query_string
```
Comment (tokers) [inline t/plugin/redirect.t:591]: Let's change the test case position to the end of the file (so there won't' have many test number changes).

File: docs/en/latest/plugins/redirect.md (hunk 2 above)
Comment (vyvyan2010) [reply docs/en/latest/plugins/redirect.md]: Done

File: t/plugin/redirect.t (hunk 4 above)
Comment (vyvyan2010) [reply t/plugin/redirect.t]: Done

File: docs/en/latest/plugins/redirect.md (hunk 3 above)
Comment (vyvyan2010) [reply docs/en/latest/plugins/redirect.md]: Done

File: t/plugin/redirect.t [hunk 5]
```diff
@@ -1114,3 +1114,38 @@ X-Forwarded-Proto: http
...
+            ngx.say(body)
+        }
+    }
+--- request
+GET /t
+--- error_code: 400
+--- response_body eval
+qr/error_msg":"failed to check the configuration of plugin redirect err: allOf 2 failed: value should match only one schema, but matches both schemas 1 and 2/
+--- no_error_log
+[error]
```
Comment (tzssangglass) [inline t/plugin/redirect.t:1151]: can we add a test case to cover the correct behavior?

File: apisix/plugins/redirect.lua [hunk 6]
```diff
@@ -55,13 +55,32 @@ local schema = {
...
+                        },
+                    },
+                },
+            },
+        },
     },
-    oneOf = {
-        {required = {"uri"}},
-        {required = {"regex_uri"}},
-        {required = {"http_to_https"}}
```
Comment (spacewander) [inline apisix/plugins/redirect.lua:63]: https://github.com/apache/apisix/blob/ccfb00055c9814f3a94514e48aa583700ab94189/apisix/schema_def.lua#L420
We can use `not` operation to show the exclusive relationship?

Comment (vyvyan2010) [reply apisix/plugins/redirect.lua:63]: I have tried, but not succeed
```
["not"] = {
    allOf = {
        {required = {"append_query_string"}},
        {required = {"http_to_https"}},
    }
}  
```
and

```
["not"] = {required = {"append_query_string", "http_to_https"}},
```

Comment (tzssangglass) [reply apisix/plugins/redirect.lua:63]:
```
http_to_https = {
    ["not"] = {required = {"uri", "regex_uri", "append_query_string"}}
},

uri = {
    ["not"] = {required = {"regex_uri", "http_to_https"}}
},

regex_uri = {
    ["not"] = {required = {"uri", "http_to_https"}}
},
```

what about this form?

Comment (spacewander) [reply apisix/plugins/redirect.lua:63]: Give it a try:
```
    oneOf = {
        {required = {"uri"}},
        {required = {"regex_uri"}},
        {required = {"http_to_https"}, ["not"] = {
           required = {"append_query_string"}
        }}
    }
```

Comment (vyvyan2010) [reply apisix/plugins/redirect.lua:63]: > Give it a try:
> 
> ```
>     oneOf = {
>         {required = {"uri"}},
>         {required = {"regex_uri"}},
>         {required = {"http_to_https"}, ["not"] = {
>            required = {"append_query_string"}
>         }}
>     }
> ```

It does work,  i have updated, please check @spacewander

File: apisix/plugins/redirect.lua (hunk 1 above)
Comment (tokers) [reply apisix/plugins/redirect.lua:58]: OK.

**Review by tokers — APPROVED** [review]

**Review by tzssangglass — APPROVED** [review]

**Review by spacewander — APPROVED** [review]
