### PR TITLE
fix: validation fails causing etcd events not to be handled correctly

### LINKED ISSUE #11267: bug: error in checking schema with etcd change event handling
### Current Behavior

> **This bug was discovered by @juzhiyuan and confirmed by @nic-6443. Thanks for their keen observations!**

When APISIX is initially started, it loads the full configuration from etcd, and when there are any changes to the configuration in etcd, APISIX will get a change event to update its memory cache.

When loading full configuration and processing change events, APISIX will check the correctness of configuration entries to weed out configurations that do not conform to the schema specification.

When checking for change events, if an event in the event set does not pass the check, it will issue an error and interrupt subsequent event processing, so some configuration changes will not be loaded and applied to the data plane.

This is wrong, it should just issue the log and skip this event and move on to the others. When the user fixes the configuration, it will go through the check and apply it in a new event.

### Expected Behavior

Only incorrect events should be skipped and the correct configuration that follows should be applied correctly.

### Error Logs

No logging, logging is interrupted when an error is triggered.

### Steps to Reproduce

1. Modify multiple resources and introduce some error entries in them.
2. you will find that there are correct configurations that should be applied that are not loaded correctly.

### Environment

- APISIX version (run `apisix version`): at least 2.0 to latest
- Operating system (run `uname -a`): independent
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): independent
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): independent
- APISIX Dashboard version, if relevant: independent
- Plugin runner version, for issues related to plugin runners: independent
- LuaRocks version, for installation issues (run `luarocks --version`): independent

### PR DESCRIPTION
**Pull request by bzp2010**
### Description

Fixes #11267

Ensure that all etcd events are handled, rather than jumping out of the execution flow when a checking error is encountered.

Current wrong behavior will cause changes in etcd to no longer take effect on the started data plane.

The issue has existed since at least APISIX 2.0, which was long, 4-5 years ago.

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: t/cli/test_etcd_sync_event_handle.sh [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+##       }
+##     },
+##     ...
+##   } },
+##   header = {
+##     ...
+##   }
+## }
+## After check, it only appears when watch recovers and returns events in bulk.
+cat logs/error.log | grep "}, {" || (echo "failed: Log case 2 unexpected"; exit 1)
```
Comment (nic-6443) [inline t/cli/test_etcd_sync_event_handle.sh:130]: assert `failed to check item data` error log too.

Comment (shreemaan-abhishek) [reply t/cli/test_etcd_sync_event_handle.sh:130]: test needs to fail if expectations are not met `||` gives a exit code 0 which is not detected as a failure by the cli testing suite.

Comment (bzp2010) [reply t/cli/test_etcd_sync_event_handle.sh:130]: @shreemaan-abhishek  Actually, the error doesn't cause the test suite to exit either, I'm not sure what's happening. But I've checked the log manually and it has no errors.

File: t/cli/test_etcd_sync_event_handle.sh [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+
+# Clean up
+make stop
```
Comment (shreemaan-abhishek) [inline t/cli/test_etcd_sync_event_handle.sh:133]: this last make stop is not needed, it is already run by default. Running twice give this error that pollutes the test output log.

image

File: t/cli/test_etcd_sync_event_handle.sh (hunk 1 above)
Comment (bzp2010) [reply t/cli/test_etcd_sync_event_handle.sh:130]: @nic-6443 Good catch! Updated.

File: t/cli/test_etcd_sync_event_handle.sh (hunk 2 above)
Comment (bzp2010) [reply t/cli/test_etcd_sync_event_handle.sh]: Fixed, that because I add the first line `. ./ci/common.sh` finally.

Comment (bzp2010) [reply t/cli/test_etcd_sync_event_handle.sh]: @shreemaan-abhishek Fixed, that because I add the first line `. ./ci/common.sh` finally.

**Review by nic-chen — APPROVED** [review]

**Review by nic-6443 — APPROVED** [review]
