### PR TITLE
change(zipkin): rearrange the child span

### LINKED ISSUE #3827: bug: the duration recorded by the zipkin plugin does not match the phase
### Issue description
The duration recorded by the zipkin plugin does not match the phase. May The plugin should be executed last, not first.

### Minimal test code / Steps to reproduce the issue
add ngx.sleep() at some other plugin's rewrite phase, the duration of access phase will be longer, instead of rewrite phase.

### PR DESCRIPTION
**Pull request by spacewander**
If you need to be compatible with the old one, you can set the
span_version to 1.

Fix #3827

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

File: apisix/plugins/zipkin.lua [hunk 1]
```diff
@@ -182,17 +186,19 @@ function _M.rewrite(plugin_conf, ctx)
...
         request_span = request_span,
-        rewrite_span = nil,
-        access_span = nil,
-        proxy_span = nil,
     }
 
     local request_span = ctx.opentracing.request_span
-    ctx.opentracing.rewrite_span = request_span:start_child_span(
-                                            "apisix.rewrite", start_timestamp)
+    if conf.span_version == 1 then
```
Comment (lilien1010) [inline apisix/plugins/zipkin.lua:192]: what about user pre-defined version const?

**Review by lilien1010 — APPROVED** [review]

File: docs/zh/latest/plugins/zipkin.md [hunk 2]
```diff
@@ -43,6 +43,29 @@ title: zipkin
...
+
+```
+request
+├── rewrite
+├── access
+└── proxy
+    └── body_filter
+```
+
+注意上述的 span 的名称跟同名的 Nginx phase 没有关系。
```
Comment (Firstsawyou) [inline docs/zh/latest/plugins/zipkin.md:66]:
```suggestion
注意：上述的 span 的名称跟同名的 Nginx phase 没有关系。
```

This should be better.

**Review by membphis — APPROVED** [review]
