### PR TITLE
fix: when only `tls.verify`, skip the logic of judging client cert

### LINKED ISSUE #12501: bug: Internal Server Error when call an API created with Admin UI to https upstream
### Current Behavior

When create routes with admin ui to https upstream then call an api via apisix then apisix response Internal server error.

Image

### Expected Behavior

Got response from upstream server

### Error Logs

```
2025/08/07 11:38:48 [error] 50#50: *83823 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/ngx/ssl.lua:448: attempt to get length of local 'pem' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/openresty/lualib/ngx/ssl.lua: in function 'parse_pem_cert'
        /usr/local/apisix/apisix/ssl.lua:216: in function 'create_obj_fun'
        /usr/local/apisix/apisix/core/lrucache.lua:95: in function 'cert_cache'
        /usr/local/apisix/apisix/ssl.lua:222: in function 'fetch_cert'
        /usr/local/apisix/apisix/upstream.lua:392: in function 'set_upstream'
        /usr/local/apisix/apisix/init.lua:562: in function 'handle_upstream'
        /usr/local/apisix/apisix/init.lua:748: in function 'http_access_phase'
        access_by_lua(nginx.conf:436):2: in main chunk, client: 192.168.65.1, server: _, request: "GET /get HTTP/1.1", host: "127.0.0.1"
```

### Steps to Reproduce

1. Run APISIX via Docker
2. Access to Admin UI
3. Create Routes with `Name: Get,  URI: /get, upstream: nodes: httpbun.com:443, scheme: https, pass_host: node` then Add
4. Access API via `curl http://127.0.0.1:9080/get` will get an Internal Server Error

**Investigate**
1.  Inspect the payload of route creating

Image

the upstream tls verify set to false

**Work around fix**

> Remove upstream tls verify

Required:
- curl
- jq

```
export ADMIN_KEY=your_admin_key_here
export ROUTE_ID=route_id
curl -s -H "X-API-KEY: $ADMIN_KEY" http://127.0.0.1:9180/apisix/admin/routes/$ROUTE_ID | jq '.value | del(.upstream.tls, .create_time)' > get.patch.json
curl -s -H "X-API-KEY: $ADMIN_KEY" http://127.0.0.1:9180/apisix/admin/routes/$ROUTE_ID -X PUT -d @get.patch.json
```

Now we can call an API via APISIX with expected response

### Environment

- APISIX version `3.13.0`
- Operating system : Docker  image `apache/apisix:3.13.0-ubuntu, Linux e58f105a038a 6.10.14-linuxkit #1 SMP Sat May 17 08:28:57 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux`

### PR DESCRIPTION
**Pull request by SkyeYoung**
### Description

In https://github.com/apache/apisix/issues/7046, a `tls.verify` property, only applicable to Kafka, was added to the upstream schema without being documented or reflected in the API. There's also a lack of handling for this property in other resources that use upstream.

So in this PR, I've added that when using non-Kafka HTTPS or gRPCs upstream, the client certificate related processing logic should be skipped when only `tls.verify`.

Considering that only the parts below in reference tls, and there are no filter-like functions provided by Lua, it's changed to check for the existence of `tls.client_cert_id` or `tls.client_cert`.

https://github.com/apache/apisix/blob/0dde7056a0bdf825bfb75e47da966a795946a48f/apisix/upstream.lua#L265-L273

#### Which issue(s) this PR fixes:

Fixes #12501 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/upstream.lua [hunk 1]
```diff
@@ -261,8 +261,8 @@ function _M.set_by_route(route, api_ctx)
     local checker = healthcheck_manager.fetch_checker(up_conf.resource_key, resource_version)
     api_ctx.up_checker = checker
     local scheme = up_conf.scheme
-    if (scheme == "https" or scheme == "grpcs") and up_conf.tls then
-
+    local tls_has_cert = up_conf.tls and (up_conf.tls.client_cert or up_conf.tls.client_cert_id)
```
Comment (bzp2010) [inline apisix/upstream.lua:264]: Just to confirm, jsonschema will ensure that if cert exists, key must also exist right?

Comment (SkyeYoung) [reply apisix/upstream.lua:264]: Yes.

https://github.com/apache/apisix/blob/598b20ff286836ac447842b2a9708d9066b805cd/apisix/schema_def.lua#L418-L424

**Review by nic-6443 — APPROVED** [review]

**Review by Baoyuantop — APPROVED** [review]
