### PR TITLE
fix(body-transformer): xml2lua: replace empty table with empty string

### LINKED ISSUE #9625: help request: body-transformer response templete troubles
### Description

Hi !

I'm experimenting with body-transformer plugin and i run into trouble , then the upstream request returns SOAP xml then there is in the  body `<Kood></Kood>` then  REST request  response  is strange    "Kood": "table: 0x7f5a42dfe048" . But then there is in body has  in between the tags like `<Kood>916</Kood>` then all works well.
Then i make many REST request there there  <Kood></Kood> the the response is diferent the part what is behind the table for example "Kood": "table: 0x7f5a42402100".

Lauri-Alo Adamson

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
apisix version
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
3.3.0

uname -a
Linux apispx 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux

openresty -V
nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
built with OpenSSL 1.1.1s  1 Nov 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.8 -DNGX_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../apisix-nginx-module-1.12.0 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/stream --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/meta --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../wasm-nginx-module-0.6.4 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../grpc-client-nginx-module-v0.4.2 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module

url http://127.0.0.1:9090/v1/server_info
{"id":"62bd3dbe-31cd-4448-ba30-810a070bad61","boot_time":1685961093,"etcd_version":"3.5.0","version":"3.3.0","hostname":"apispx"}

### PR DESCRIPTION
**Pull request by kingluo**
### Description

Fixes #9625

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by AlinsRan — APPROVED** [review]

File: apisix/plugins/body-transformer.lua [hunk 1]
```diff
@@ -123,6 +128,8 @@ local function transform(conf, body, typ, ctx)
                 core.log.error(err, ", body=", body)
                 return nil, 400, err
             end
+        else
+            ngx.log(ngx.WARN, "no input format to parse ", typ, " body")
```
Comment (leslie-tsang) [inline apisix/plugins/body-transformer.lua:132]: Please use `core.log.error` instead

**Review by leslie-tsang — CHANGES_REQUESTED** [review]

File: t/plugin/body-transformer.t [hunk 2]
```diff
@@ -821,3 +821,75 @@ location /demo {
...
+            local uri = "http://127.0.0.1:" .. ngx.var.server_port .. "/ws"
+            local opt = {method = "GET"}
+            local httpc = http.new()
+            local res = httpc:request_uri(uri, opt)
+            assert(res.status == 200)
+            local data1 = core.json.decode(res.body)
+            local data2 = core.json.decode[[{"KOVKood":""}]]
+            assert(core.json.stably_encode(data1) == core.json.stably_encode(data2))
+        }
+    }
```
Comment (monkeyDluffy6017) [inline t/plugin/body-transformer.t:895]:
```suggestion
    location /demo {
        content_by_lua_block {
            ngx.print([[
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xrd="http://x-road.eu/xsd/xroad.xsd" xmlns:prod="http://rr.x-road.eu/producer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:id="http://x-road.eu/xsd/identifiers" xmlns:repr="http://x-road.eu/xsd/representation.xsd" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/">
    <SOAP-ENV:Body>
        <prod:RR58isikEpiletResponse>
        <request><Isikukood>33333333333</Isikukood></request>
        <response>
            <Isikukood>33333333333</Isikukood>
            <KOVKood></KOVKood>
        </response>
        </prod:RR58isikEpiletResponse>
    </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
            ]])
        }
    }

    location /t {
        content_by_lua_block {
            local t = require("lib.test_admin")
            local rsp_template = ngx.encode_base64[[
{ "KOVKood":"{{Envelope.Body.RR58isikEpiletResponse.response.KOVKood}}" }
            ]]

            local code, body = t.test('/apisix/admin/routes/1',
                ngx.HTTP_PUT,
                string.format([[{
                    "uri": "/ws",
                    "plugins": {
                        "proxy-rewrite": {
                            "uri": "/demo"
                        },
                        "body-transformer": {
                            "response": {
                                "template": "%s"
                            }
                        }
                    },
                    "upstream": {
                        "type": "roundrobin",
                        "nodes": {
                            "127.0.0.1:%d": 1
                        }
                    }
                }]], rsp_template, ngx.var.server_port)
            )
            if code >= 300 then
                ngx.status = code
                return
            end
            ngx.sleep(0.5)

            local core = require("apisix.core")
            local http = require("resty.http")
            local uri = "http://127.0.0.1:" .. ngx.var.server_port .. "/ws"
            local opt = {method = "GET"}
            local httpc = http.new()
            local res = httpc:request_uri(uri, opt)
            assert(res.status == 200)
            
            local data1 = core.json.decode(res.body)
            local data2 = core.json.decode[[{"KOVKood":""}]]
            assert(core.json.stably_encode(data1) == core.json.stably_encode(data2))
        }
    }
```

File: apisix/plugins/body-transformer.lua [hunk 3]
```diff
@@ -123,6 +128,8 @@ local function transform(conf, body, typ, ctx)
                 core.log.error(err, ", body=", body)
                 return nil, 400, err
             end
+        else
+            core.log.warn("no input format to parse ", typ, " body")
```
Comment (monkeyDluffy6017) [inline apisix/plugins/body-transformer.lua:132]: It should return 400 if the `format` is nil

Comment (kingluo) [reply apisix/plugins/body-transformer.lua:132]: The format is optional! Notice the document for the requirement before you make a suggestion.
Here it's just a warning log to remind the user.

File: t/plugin/body-transformer.t (hunk 2 above)
Comment (kingluo) [reply t/plugin/body-transformer.t:895]: What's your opinion? Why make this change? Please describe it.

File: apisix/plugins/body-transformer.lua (hunk 3 above)
Comment (monkeyDluffy6017) [reply apisix/plugins/body-transformer.lua:132]: It will return 500 if there are no `content-type` and `input_format`

File: t/plugin/body-transformer.t (hunk 2 above)
Comment (monkeyDluffy6017) [reply t/plugin/body-transformer.t:895]: I format the code for you, just copy and paste it

File: apisix/plugins/body-transformer.lua (hunk 3 above)
Comment (kingluo) [reply apisix/plugins/body-transformer.lua:132]: Check https://github.com/apache/apisix/blob/e19a46663f6cbf2d2a91027b2887cfdbebf70dbc/t/plugin/body-transformer.t#L458

Comment (kingluo) [reply apisix/plugins/body-transformer.lua:132]: The input_format nil case is for manual parsing by the user via template code block, which is the expected case in the proposal! For example, for the time being, we don't support yaml parsing, then what if the user needs to parse himself? We should enable him to do this via this plugin, but not 500! We cannot handle all content types in the world. And you should not assume the content type exists, especially for unknown and unmanaged upstream websites. Since we cannot support all types to parse the body, what's the meaning to ensure content_type or input_format exists? After all, for unknown types, the user is in charge of parsing via the template.

In TEST 12, the XML format is expected, so it's expected to accept input_format as XML. The user should ensure the template matches the actual input content. Think that what if the user composes an invalid template even for the correct type and content, it will still raise errors for non-exist fields! Then how to handle this case? That is, you cannot avoid such errors you show only via configuration sanity check!

**And, the most important is, please do not argue the proposal and requirement in this PR, if you're in doubt, you can propose your opinion via the mailing list and describe your change request there!**

**This PR is for empty xml value bugfix only!**

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by leslie-tsang — APPROVED** [review]
