### PR TITLE
fix: check if `config` contains duplicate resources in API-driven standalone mode

### LINKED ISSUE #12259: bug: API-driven standalone mode does not properly handle resources with duplicate IDs
### Current Behavior

When two services with the same ID are entered (in fact, any resource), the Admin API accepts the input.
When fetching resources via GET, resources with the same ID are output.

### Expected Behavior

Only one of multiple duplicate ID resources should be accepted. And reject the input if it is completely unprocessable, e.g., both ID and modifiedIndex are the same.

### Error Logs

_No response_

### Steps to Reproduce

```json
{
    "ssls_conf_version": 0,
    "consumer_groups_conf_version": 1,
    "protos_conf_version": 1,
    "secrets_conf_version": 1,
    "plugin_metadata_conf_version": 0,
    "services": [
        {
            "modifiedIndex": 4,
            "desc": "desc",
            "name": "service1",
            "upstream": {
                "scheme": "https",
                "nodes": [
                    {
                        "host": "httpbin.org",
                        "weight": 100,
                        "port": 443
                    }
                ]
            },
            "id": "6e899c1108b88e75d4887b85f9a62c26d9571739",
            "hosts": [
                "example1.com",
                "example2.com"
            ]
        },
        {
            "modifiedIndex": 1,
            "id": "6e899c1108b88e75d4887b85f9a62c26d9571739",
            "name": "service1",
            "hosts": [
                "example1.com",
                "example2.com"
            ],
            "upstream": {
                "scheme": "https",
                "nodes": [
                    {
                        "host": "httpbin.org",
                        "port": 443,
                        "weight": 100
                    }
                ]
            }
        },
        {
            "modifiedIndex": 1,
            "id": "45d48919804fadc2db9d0180a65fe0ee0a8ddf9a",
            "name": "service2",
            "upstream": {
                "scheme": "https",
                "nodes": [
                    {
                        "host": "httpbin.org",
                        "port": 443,
                        "weight": 100
                    }
                ]
            }
        }
    ],
    "upstreams_conf_version": 0,
    "routes_conf_version": 0,
    "services_conf_version": 6,
    "plugin_configs_conf_version": 1,
    "consumers_conf_version": 0,
    "global_rules_conf_version": 0,
    "stream_routes_conf_version": 0
}
```

```shell
#1 update
curl http://localhost:19180/apisix/admin/configs -H "x-api-key: edd1c9f034335f136f87ad84b625c8f1" -XPUT --data '{"ssls_conf_version":0,"consumer_groups_conf_version":1,"protos_conf_version":1,"secrets_conf_version":1,"plugin_metadata_conf_version":0,"services":[{"modifiedIndex":4,"desc":"desc","name":"service1","upstream":{"scheme":"https","nodes":[{"host":"httpbin.org","weight":100,"port":443}]},"id":"6e899c1108b88e75d4887b85f9a62c26d9571739","hosts":["example1.com","example2.com"]},{"modifiedIndex":1,"id":"6e899c1108b88e75d4887b85f9a62c26d9571739","name":"service1","hosts":["example1.com","example2.com"],"upstream":{"scheme":"https","nodes":[{"host":"httpbin.org","port":443,"weight":100}]}},{"modifiedIndex":1,"id":"45d48919804fadc2db9d0180a65fe0ee0a8ddf9a","name":"service2","upstream":{"scheme":"https","nodes":[{"host":"httpbin.org","port":443,"weight":100}]}}],"upstreams_conf_version":0,"routes_conf_version":0,"services_conf_version":6,"plugin_configs_conf_version":1,"consumers_conf_version":0,"global_rules_conf_version":0,"stream_routes_conf_version":0}'
```

```shell
#2 get
curl http://localhost:19180/apisix/admin/configs -H "x-api-key: edd1c9f034335f136f87ad84b625c8f1"
```

### Environment

- APISIX version (run `apisix version`): master
- Operating system (run `uname -a`): N/A
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): N/A
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): N/A
- APISIX Dashboard version, if relevant: N/A
- Plugin runner version, for issues related to plugin runners: N/A
- LuaRocks version, for installation issues (run `luarocks --version`): N/A

### PR DESCRIPTION
**Pull request by LiteSun**
### Description
add duplicate resource check in API-driven standalone mode

#### Which issue(s) this PR fixes:

Fixes #12259 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/admin/standalone.lua [hunk 1]
```diff
@@ -34,6 +34,25 @@ local EVENT_UPDATE = "standalone-api-configuration-update"
 
 local _M = {}
 
+local function check_duplicate(item, key, id_set)
```
Comment (membphis) [inline apisix/admin/standalone.lua:37]: which is much clearer:

```lua
local duplicated, err = check_duplicate(item, key, id_set)
```

File: apisix/admin/standalone.lua [hunk 2]
```diff
@@ -167,6 +187,13 @@ local function update(ctx)
                         core.response.exit(400, {error_msg = err_prefix .. err})
                     end
                 end
+                -- check duplicate resource
+                local err = check_duplicate(item, key, id_set)
+                if err then
+                    core.log.error(err)
```
Comment (membphis) [inline apisix/admin/standalone.lua:191]: pls add more comments, make it easier to read

**Review by membphis — CHANGES_REQUESTED** [review]

File: t/admin/standalone.t [hunk 3]
```diff
@@ -208,3 +208,33 @@ x-apisix-conf-version-routes: 100
...
+    location /t11 {}
+--- request
+PUT /apisix/admin/configs
+{"routes_conf_version":1063,"routes":[{"id":"r1","uri":"/r2","upstream_id":"u1","plugins":{"proxy-rewrite":{"uri":"/hello"}}},
+{"id":"r1","uri":"/r2","upstream_id":"u1","plugins":{"proxy-rewrite":{"uri":"/hello"}}}]}
+--- more_headers
+X-API-KEY: edd1c9f034335f136f87ad84b625c8f1
+--- error_code: 400
+--- response_body
+{"error_msg":"duplicate id found r1"}
```
Comment (bzp2010) [inline t/admin/standalone.t]: Please include the resource type in error message.

File: t/admin/standalone.t [hunk 4]
```diff
@@ -208,3 +208,33 @@ x-apisix-conf-version-routes: 100
...
+    location /t12 {}
+--- request
+PUT /apisix/admin/configs
+{"consumers_conf_version":1064,"consumers":[{"username":"consumer1","plugins":{"key-auth":{"key":"consumer1"}}},
+{"username":"consumer1","plugins":{"key-auth":{"key":"consumer1"}}}]}
+--- more_headers
+X-API-KEY: edd1c9f034335f136f87ad84b625c8f1
+--- error_code: 400
+--- response_body
+{"error_msg":"duplicate username found consumer1"}
```
Comment (bzp2010) [inline t/admin/standalone.t]: ditto
