### PR TITLE
fix(consul): retry connecting after a delay

### LINKED ISSUE #4632: bug: When the service kv does not exist, the fetch timer of consul_kv will fetch service data frantically, resulting in 100% CPU
当服务kv不存在时consul_kv的fetch timer会疯狂获取服务数据导致CPU 100%

2021/07/20 07:11:55 [error] 42#42: *193170 [lua] consul_kv.lua:329: connect consul: http://10.242.154.205:8500/v1/kv/ by key: /kv/apisix-service-upstreams, got result: null, with error: timeout, context: ngx.timer

目测是因为_M.connect异常后直接再次跳转到:: ERR ::再次尝试_M.connect~ 死循环了

### PR DESCRIPTION
**Pull request by spacewander**
Fix #4632
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

**Review by shuaijinchao — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

File: apisix/discovery/consul_kv.lua [hunk 1]
```diff
@@ -331,6 +332,15 @@ function _M.connect(premature, consul_server)
             ", got result: ", json_delay_encode(result, true),
             ", with error: ", error_info)
 
+        if not retry_delay then
+            retry_delay = 1
+        else
+            retry_delay = retry_delay * 4
```
Comment (tokers) [inline apisix/discovery/consul_kv.lua:338]: Why here we use `4` as the factor?

Comment (spacewander) [reply apisix/discovery/consul_kv.lua:338]: Discussed in https://github.com/apache/apisix/issues/4632#issuecomment-883184083

Comment (spacewander) [reply apisix/discovery/consul_kv.lua:338]: 2 is not large enough for me.

**Review by tokers — APPROVED** [review]

**Review by tzssangglass — APPROVED** [review]
