### PR TITLE
fix: closing brace should not be a part of variable

### LINKED ISSUE #10478: bug: incorrect variable extraction in the configuration
### Current Behavior

When I use the fault-injection plugin as:

```
curl http://127.0.0.1:9180/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "plugins": {
       "fault-injection": {
           "abort": {
              "http_status": 200,
              "body": "{\"count\": $arg_count}"
           }
       }
    },
    "upstream": {
       "nodes": {
           "127.0.0.1:1980": 1
       },
       "type": "roundrobin"
    },
    "uri": "/hello"
}'
```
I get the response:
```
$ curl http://127.0.0.1:9080/hello\?count\=3
{"count": 3 
```

### Expected Behavior

It seems to be missing the right brace, although it's also to walk around by: `"body": "{\"count\": ${arg_count}}"`

[Relevant code](https://github.com/apache/apisix/blob/release/3.6/apisix/core/utils.lua#L295) :
```lua
local resolve_var
do
    local _ctx
    local n_resolved
    local pat = [[(?<!\\)\$\{?(\w+)\}?]]
...
```

Can it be modified to like `[[(?<!\\)\$(\{(\w+)\}|(\w+))]]`? Otherwise, expressions like `${a` and `$a}` will both be extracted as variables, which seems a bit confusing.

### Error Logs

_No response_

### Steps to Reproduce

1. Run APISIX via the Docker image.
2. Using the above configuration and curl.

### Environment

- APISIX version (run `apisix version`):3.6.0
- Operating system (run `uname -a`): NA
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):NA
- APISIX Dashboard version, if relevant: NA
- Plugin runner version, for issues related to plugin runners: NA
- LuaRocks version, for installation issues (run `luarocks --version`): NA

### PR DESCRIPTION
**Pull request by shreemaan-abhishek**
### Description

Current regex for evaluating variables like: `$var`, `${var}`, etc. would also match `$var}` including the closing brace. This has been fixed.

Fixes #10478

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

**Review by Sn0rt — APPROVED** [review]

**Comment by monkeyDluffy6017** [comment]
please make the ci pass

**Comment by shreemaan-abhishek** [comment]
done

**Review by dramenk — APPROVED** [review]

File: apisix/core/utils.lua [hunk 1]
```diff
@@ -292,11 +292,16 @@ local resolve_var
...
     local _escaper
 
     local function resolve(m)
-        local v = _ctx[m[1]]
+        local i = 1
+        -- if first capture's first char is "{" evaluate the second capture
+        if m[1]:byte(1) == 123 then
+            i = 2
+        end
+        local v = _ctx[m[i]]
```
Comment (monkeyDluffy6017) [inline apisix/core/utils.lua:304]: Why do you add this?

Comment (shreemaan-abhishek) [reply apisix/core/utils.lua:304]: this was to fix other test case failures. For example when var = `${alpha}`, m[1] = {alpha} and m[2] = alpha. Only m[2] can be evaluated no m[1].

File: apisix/core/utils.lua [hunk 2]
```diff
@@ -292,11 +292,16 @@ local resolve_var
...
     local n_resolved
-    local pat = [[(?<!\\)\$\{?(\w+)\}?]]
+    local pat = [[(?<!\\)\$(\{(\w+)\}|(\w+))]]
     local _escaper
 
     local function resolve(m)
-        local v = _ctx[m[1]]
+        local i = 1
+        -- if first capture's first char is "{" evaluate the second capture
+        if m[1]:byte(1) == 123 then
```
Comment (monkeyDluffy6017) [inline apisix/core/utils.lua:301]: I think you can optimise this judgement, like
```
local variable = m[2] or m [3]
local v = _ctx[variable]
```

   


```

Comment (shreemaan-abhishek) [reply apisix/core/utils.lua]: it works

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by AlinsRan — APPROVED** [review]
