### PR TITLE
fix: proxy grpc sometimes occurs 502

### LINKED ISSUE #8166: help request: proxy grpc sometimes occurs 502
### Description

hello:
 we have two apisix env(such as A and B),  when we use apisix to proxy grpc service,  A always OK, but in B, when you first time send a request. It returns 502, but the following request all returns 200. and I also found that when we send a request in B, after a while，send request again, then the first request always return 502, the following return 200. I am confused of such thing. because A and B env apisix version and depends are same. 
  
 when 502 occurs. the following error occurs:
`

    [error] 20620#20620: *327238 no connection data found for keepalive http2 connection while sending request to upstream

`

I want to get some idea from you.  what causes it and how to solve it. 
hope yours. thanks.

### Environment

- APISIX version (run `apisix version`): v2.12.0
- Operating system (run `uname -a`): the problem env is :Linux 3.10.0-1160.36.2.el7.x86_64. the good env is: Linux 3.10.0-957.21.3.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by soulbird**
### Description

Fixes #8166 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: t/grpc_server_example/main.go [hunk 1]
```diff
@@ -217,6 +223,21 @@ func (s *server) Run(ctx context.Context, in *pb.Request) (*pb.Response, error)
...
 }
 
+func gRPCAndHTTPFunc(grpcServer *grpc.Server) http.Handler {
+	return h2c.NewHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		mux := http.NewServeMux()
+		mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
+			w.Write([]byte("hello http"))
+		})
+
+		if r.ProtoMajor == 2 && strings.Contains(r.Header.Get("Content-Type"), "application/grpc") {
```
Comment (tokers) [inline t/grpc_server_example/main.go:233]: Try the https://pkg.go.dev/github.com/brankas/netmux.

**Review by spacewander — APPROVED** [review]

**Review by tzssangglass — APPROVED** [review]

File: t/grpc_server_example/main.go (hunk 1 above)
Comment (soulbird) [reply t/grpc_server_example/main.go:233]: It looks like this is a library for routing distributions? It doesn't have any documentation description. For this test case, I think it would be better to be simple and direct, and there is no performance pursuit.

Comment (tokers) [reply t/grpc_server_example/main.go:233]: No, this is for protocol sniffing.

Comment (tokers) [reply t/grpc_server_example/main.go:233]: Sorry, I sent a wrong repo, please ignore it.
