### PR TITLE
fix: use shdict instead of events module for nodes data exchange

### LINKED ISSUE #12398: bug: 503 errors occur after restarting APISIX when using Consul and APISIX both in Docker
### Current Behavior

Restarting APISIX while it is handling continuous requests leads to intermittent 503 Service Unavailable responses.

I have prepared a minimal reproducible setup. The file structure looks like this:

```
├── apisix
│   ├── apisix.yaml
│   └── config.yaml
├── nginx
│   └── default.conf
├── init.sh
├── restart.sh
└── test.sh

```

Once unpacked, the issue can be reproduced easily on any machine that has Docker and curl installed.

1. Run init.sh to launch Consul and the upstream NGINX container that APISIX will route traffic to.
2. Run restart.sh to start APISIX.
3. Run test.sh, which sends continuous requests to APISIX. At first, all responses should return HTTP status code 200.
4. While test.sh is running, repeatedly execute restart.sh to restart APISIX.
5. After restarting, even when the new APISIX instance is up and running normally, you will still see intermittent 503 errors in the output of test.sh.

This indicates that APISIX fails to route traffic correctly after a restart, despite the upstream and service discovery being healthy.

### Expected Behavior

After restarting APISIX, once it has successfully started and is healthy, it should be able to route traffic to upstream services registered in Consul without returning 503 errors.

### Error Logs

When test.sh starts to show 503 responses, you can check the APISIX container logs to see detailed error messages. These logs provide insight into why the requests failed, such as upstream discovery or routing issues.

### Steps to Reproduce

1. Unpack the minimal test setup files.
2. Run: ./init.sh
3. Start APISIX: ./restart.sh
4. Start testing: ./test.sh
5. In a separate terminal, repeatedly run: ./restart.sh
6. Watch test.sh output — it will gradually show 503 errors.

### Environment

[apisix-debug.zip](https://github.com/user-attachments/files/21035829/apisix-debug.zip)

### PR DESCRIPTION
**Pull request by shreemaan-abhishek**
### Description

Fixes #12398

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/discovery/consul/init.lua [hunk 1]
```diff
@@ -149,14 +162,21 @@ local function read_dump_services()
...
-    log.info("load dump file into memory success")
+    for k, v in pairs(entity.services) do
+        local content, json_err = core.json.encode(v)
+        if content then
+            consul_dict:set(k, content)
+        else
+            log.error("failed to encode dump service: ", k, ", error: ", json_err)
+        end
+    end
+    log.info("load dump file into shared dict success")
```
[the remark this answers is not in the document]
Comment (shreemaan-abhishek) [reply apisix/discovery/consul/init.lua:214]: since the values are set using service keys, I don't think this should be of concern.

File: apisix/discovery/consul/init.lua [hunk 2]
```diff
@@ -66,53 +73,73 @@ local _M = {
...
+    return services
 end
 
 
 function _M.nodes(service_name)
-    if not all_services then
-        log.error("all_services is nil, failed to fetch nodes for : ", service_name)
-        return
+    local value = consul_dict:get(service_name)
+    if not value then
```
[the remark this answers is not in the document]
Comment (shreemaan-abhishek) [reply apisix/discovery/consul/init.lua]: we don't want stale values, so we can ignore this.

File: apisix/discovery/consul/init.lua [hunk 3]
```diff
@@ -611,35 +637,32 @@ end
...
     end
+
+    if process.type() ~= "privileged agent" then
+        return
+    end
+
+    -- flush stale data that may persist across reloads,
+    -- since consul_services is re-initialized empty
+    consul_dict:flush_all()
+
```
[the remark this answers is not in the document]
Comment (shreemaan-abhishek) [reply apisix/discovery/consul/init.lua:693]: the `stale` data mentioned in the comment does not mean "data that has expired", it means data that is no longer up to date according to consuls state. So we should avoid flushing only expired data to obtain a clean slate upon restart.

File: apisix/discovery/consul/init.lua (hunk 2 above)
[the remark this answers is not in the document]
Comment (shreemaan-abhishek) [reply apisix/discovery/consul/init.lua]: we don't want expired shdict data so we should skip this.

File: apisix/discovery/consul/init.lua [hunk 4]
```diff
@@ -611,35 +637,32 @@ end
...
         default_service.weight = default_weight
     end
+
+    if process.type() ~= "privileged agent" then
+        return
+    end
+
+    -- flush stale data that may persist across reloads,
+    -- since consul_services is re-initialized empty
+    consul_dict:flush_all()
```
[the remark this answers is not in the document]
Comment (shreemaan-abhishek) [reply apisix/discovery/consul/init.lua:692]: in this context `stale data` does not mean expired shdict data. Stale means data that is not up to date according to the state in consul. The idea behind doing `flush_all` is to start with a clean slate.

File: apisix/discovery/consul/init.lua (hunk 3 above)
[the remark this answers is not in the document]
Comment (shreemaan-abhishek) [reply apisix/discovery/consul/init.lua:693]: this bug was only reproducible when apisix was deployed in docker.

File: apisix/discovery/consul/init.lua [hunk 5]
```diff
@@ -149,14 +176,21 @@ local function read_dump_services()
...
+    log.info("load dump file into shared dict success")
 end
 
 
 local function write_dump_services()
     local entity = {
-        services = all_services,
+        services = _M.all_nodes(),
         last_update = ngx.time(),
         expire = dump_params.expire, -- later need handle it
```
[the remark this answers is not in the document]
Comment (shreemaan-abhishek) [reply apisix/discovery/consul/init.lua:231]: done

File: apisix/discovery/consul/init.lua [hunk 6]
```diff
@@ -66,53 +73,82 @@ local _M = {
...
-        ", all services: ", json_delay_encode(all_services, true))
-end
-
-
 function _M.all_nodes()
-    return all_services
+    local keys = consul_dict:get_keys(0)
+    local services = core.table.new(0, #keys)
+    for _, key in ipairs(keys) do
+        local value = consul_dict:get(key)
```
Comment (membphis) [inline apisix/discovery/consul/init.lua:102]: After calculating every 10~20 keys, call `ngx.sleep(0)`

File: apisix/discovery/consul/init.lua [hunk 7]
```diff
@@ -66,53 +73,82 @@ local _M = {
...
 
 
 function _M.nodes(service_name)
-    if not all_services then
-        log.error("all_services is nil, failed to fetch nodes for : ", service_name)
-        return
+    local value = consul_dict:get(service_name)
+    if not value then
+        log.error("consul service not found: ", service_name, ", return default service")
+        nodes_cache[service_name] = nil
```
Comment (membphis) [inline apisix/discovery/consul/init.lua]: `nodes_cache`

This cache may contain some useless, expired data. To prevent it from growing indefinitely, it needs to be cleaned up periodically (deleting useless cached data).

Another way,  an LRU (Local Redirect) approach can be used for easier and more direct control over the cache size.

**Review by membphis — CHANGES_REQUESTED** [review]

File: apisix/cli/ngx_tpl.lua [hunk 8]
```diff
@@ -78,6 +78,7 @@ lua {
     lua_shared_dict status-report {* meta.lua_shared_dict["status-report"] *};
     {% end %}
     lua_shared_dict nacos 10m;
+    lua_shared_dict consul 10m;
```
Comment (membphis) [inline apisix/cli/ngx_tpl.lua]: 10m is not enough for everyone

Allow users to customize configurations

File: apisix/discovery/consul/init.lua [hunk 9]
```diff
@@ -66,53 +73,80 @@ local _M = {
...
-    return resp_list
+    return nodes
 end
 
 
 local function update_all_services(consul_server_url, up_services)
-    -- clean old unused data
+    -- write new/updated values first so readers never see a missing service
+    for k, v in pairs(up_services) do
+        local content, err = core.json.encode(v)
```
Comment (membphis) [inline apisix/discovery/consul/init.lua:139]: need the same way too

```
if i % 100 == 0 then
            ngx.sleep(0)
        end
```

**Review by membphis — DISMISSED** [review]

**Review by Baoyuantop — APPROVED** [review]

File: apisix/discovery/consul/init.lua [hunk 10]
```diff
@@ -66,53 +73,85 @@ local _M = {
...
+    return services
 end
 
 
 function _M.nodes(service_name)
-    if not all_services then
-        log.error("all_services is nil, failed to fetch nodes for : ", service_name)
-        return
+    local value = consul_dict:get(service_name)
+    if not value then
```
Comment (bzp2010) [inline apisix/discovery/consul/init.lua]: Each request using service discovery will directly retrieve from shdict, which I suspect may cause lock contention.
Why not adopt the following pattern:

1. Retrieve the node for the service name from lrucache. If present, it will return quickly without contention.
2. If service does not exist in lrucache, retrieve authoritative data prepared by privileged processes via the initialization function from shdict. Lrucache will then cache and return these.
3. If the shdict also doesn't contain it, it's best to log the "not found" result in lrucache to prevent an unexpected service name from consistently bypassing the fast path cache. It will be cached via `neg_ttl`, https://github.com/apache/apisix/blob/master/apisix/core/lrucache.lua#L130.

This ensures most requests complete on the fast path without accessing shdict. Only the next cache hit after a miss will fetch from shdict.
The way currently being adopted is exactly the opposite.

Comment (bzp2010) [reply apisix/discovery/consul/init.lua]: cc @membphis WDYT?

Comment (shreemaan-abhishek) [reply apisix/discovery/consul/init.lua]: > The way currently being adopted is exactly the opposite.

I don't think so, the lrucache usage helps cache the the json decode operation.

If we use an lrucache to cache the node for a given service name we don't have a good way to invalidate the lrucache when service data changes. Since privileged_agent is the only one that fetches data from consul a shdict is the only way to let other workers know that consul data has changed. Hence, we would still need to retrieve data from shdict if we want to use lrucache like you said.

Comment (bzp2010) [reply apisix/discovery/consul/init.lua]: What I'm referring to is a unidirectional process where each layer relies on its own TTL to control data expiration. Lower levels (privileged process, shdict) do not proactively invalidate higher-level (lrucache) caches. As long as the TTL is sufficiently small, changes take effect quickly. This process is entirely controlled by hard-coded values or configuration settings.

On the fast path, JSON decoding never occurs because we never fetch the raw JSON-encoded text from the shdict each time. We always use the already-cached table.

If we set the lrucache TTL to 1s, service node updates will take effect within 1 second. During this 1-second cache period, shdict is not read, eliminating lock contention. Moreover, since the data is read and parsed from shdict only once, JSON decoding does not occur (this is also an advantage of the worker-level LRU cache, whose scope is confined to a single worker. Consequently, there is no concurrency in populating the LRU cache, thereby saving the decoding overhead for each service_name). Of course, we can also set it to 0.1 seconds or 60 seconds—it's a balance between response speed and overhead.

Therefore, I have never considered JSON decoding to be an issue.
