### PR TITLE
fix(nacos): distinguish services that has same name but in different groups or namespaces

### LINKED ISSUE #5061: bug：nacos.lua 脚本 同样的服务名称不同分组的实例，会存储到同一个nacos服务节点中
### Issue description

image
同样的服务名称，不同分组，通过nacos.lua分组后，不同分组的实例都会注册到同一个服务底下。

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### PR DESCRIPTION
**Pull request by tzssangglass**
### What this PR does / why we need it:

fix #5061
### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

### CODE REVIEW

File: apisix/discovery/nacos.lua [hunk 1]
```diff
@@ -307,11 +311,21 @@ local function fetch_full_registry(premature)
...
+        end
+
+        if not up_apps[namespace_id][group_name] then
+            up_apps[namespace_id][group_name] = {}
+        end
+
         for _, host in ipairs(data.hosts) do
-            local nodes = up_apps[service_info.service_name]
+            local nodes = up_apps[namespace_id]
+            [group_name][service_info.service_name]
```
Comment (shuaijinchao) [inline apisix/discovery/nacos.lua:324]: It will be better to merge it into one line for readability.

**Comment by tzssangglass** [comment]
base on https://github.com/api7/nacos-test-service/pull/2

File: apisix/discovery/nacos.lua (hunk 1 above)
Comment (tzssangglass) [reply apisix/discovery/nacos.lua:324]: done

**Review by nic-chen — APPROVED** [review]

File: apisix/discovery/nacos.lua (hunk 1 above)
Comment (spacewander) [inline apisix/discovery/nacos.lua:324]: Better to add an indent here

File: apisix/discovery/nacos.lua [hunk 2]
```diff
@@ -307,11 +311,21 @@ local function fetch_full_registry(premature)
...
             if not nodes then
                 nodes = {}
-                up_apps[service_info.service_name] = nodes
+                up_apps[namespace_id]
+                [group_name][service_info.service_name] = nodes
```
Comment (spacewander) [inline apisix/discovery/nacos.lua:328]: Ditto

File: apisix/discovery/nacos.lua [hunk 3]
```diff
@@ -235,12 +237,12 @@ local function iter_and_add_service(services, values)
 
         local namespace_id
         if up.discovery_args then
-            namespace_id = up.discovery_args.namespace_id
+            namespace_id = up.discovery_args.namespace_id or default_namespace_id
```
Comment (spacewander) [inline apisix/discovery/nacos.lua:240]: Look like the default value is not necessary here? We already use one in fetch_full_registry

Comment (tzssangglass) [reply apisix/discovery/nacos.lua:240]: the data of `fetch_full_registry` is from nacos, and the data of `up.discovery_args` is from `conf`, so it's necessary here.

File: apisix/discovery/nacos.lua (hunk 2 above)
Comment (tzssangglass) [reply apisix/discovery/nacos.lua]: done

File: apisix/discovery/nacos.lua (hunk 1 above)
Comment (tzssangglass) [reply apisix/discovery/nacos.lua]: done

**Review by spacewander — APPROVED** [review]

**Review by shuaijinchao — APPROVED** [review]
