### PR TITLE
fix: traffic split plugin not validating upstream_id

### LINKED ISSUE #9996: bug: traffic-split plugin does not verify the UpstreamID is valid
### Current Behavior

when i use traffic-split on a route,if i use a not exist upstream id,it will not verify this upstream id is valid.
`{
    "uri": "/index.html",
    "plugins": {
        "traffic-split": {
            "rules": [
                {
                    "weighted_upstreams": [
                        {
                            "upstream_id": "abcdefg",//this upstreamid is not exist,but this request will success
                            "weight": 1
                        },
                        {
                            "weight": 1
                        }
                    ]
                }
            ]
        }
    },
    "upstream_id": "abcdefg",//this upstreamid is not exist,but this request will failed
}` 

### Expected Behavior

_No response_

### Error Logs

_No response_

### Steps to Reproduce

set traffic-split plugin on route,and set a not exist upstreamid

### Environment

- APISIX version (run `apisix version`):3.3
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by shreemaan-abhishek**
### Description

Fixes #9996

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/plugins/traffic-split.lua [hunk 1]
```diff
@@ -233,6 +233,27 @@ function _M.access(conf, ctx)
     local match_passed = true
 
     for _, rule in ipairs(conf.rules) do
+        -- check if all upstream_ids are valid
+        if rule.weighted_upstreams then
+            for _, wupstream in ipairs(rule.weighted_upstreams) do
+                local upstream_id = wupstream.upstream_id
+                if upstream_id then
+                    local key = "/upstreams/" .. upstream_id
+                    local res, err = core.etcd.get(key)
```
Comment (jiangfucheng) [inline apisix/plugins/traffic-split.lua:242]: Can we use `upstream.get_by_id(upstream_id) instead of this logic?

Comment (shreemaan-abhishek) [reply apisix/plugins/traffic-split.lua]: I agree, the current scenario does not cover standalone mode.

File: t/plugin/traffic-split.t
Comment (jiangfucheng) [inline t/plugin/traffic-split.t:1]: Why we need remove these tests?

Comment (shreemaan-abhishek) [reply t/plugin/traffic-split.t:1]: Mistake 😂, let me fix it.

**Comment by jiangfucheng** [comment]
@shreemaan-abhishek Please take a look the failed CI.

**Review by jiangfucheng — APPROVED** [review]

**Review by moonming — APPROVED** [review]

**Comment by Nobilta** [comment]
@shreemaan-abhishek @jiangfucheng Hi,everyone,when i test this function in apisix3.5,this error is still exist
image

**Comment by Nobilta** [comment]
> @shreemaan-abhishek @jiangfucheng Hi,everyone,when i test this function in apisix3.5,this error is still exist image
In both the patch and put methods
image

**Comment by Nobilta** [comment]
@shreemaan-abhishek @jiangfucheng  we can modify check_schema function in traffic-split.lua and add the validating function.
image

`function _M.check_schema(conf)
    local ok, err = core.schema.check(schema, conf)

    if not ok then
        return false, err
    end

    if conf.rules then
        for _, rule in ipairs(conf.rules) do
            if rule.match then
                for _, m in ipairs(rule.match) do
                    local ok, err = expr.new(m.vars)
                    if not ok then
                        return false, "failed to validate the 'vars' expression: " .. err
                    end
                end
            end
            if rule.weighted_upstreams then
                for _, wupstream in ipairs(rule.weighted_upstreams) do
                    local ups_id = wupstream.upstream_id
                    if ups_id then
                        local ups = upstream.get_by_id(ups_id)
                        core.log.error("upstream:", ups)
                        if not ups then
                            return false, "failed to fetch upstream info by "
                                        .. "upstream id: " .. ups_id
                        end
                    end
                end
            end
        end
    end

    return true
end`
