### PR TITLE
fix(docker): support valid YAML variations in standalone mode

### LINKED ISSUE #12427: bug: docker image standalone check fails on valid config files
### Current Behavior

In the apisix docker image, the `/check_standalone_config.sh`  checks that the config is in "standalone mode". However it uses hard-coded greps for strings in the yaml such as `role: data_plane`. This means the check will fail if the yaml is formated even slightly different, e.g.
```yaml
deployment:
  role: "data_plane"
```
or 
```yaml
deployment: {"role": "data_plane"}
```

Also, the check does not respect the `APISIX_PROFILE` environment variable and so will be looking in the wrong config file entirely if you are using multiple profiles.

### Expected Behavior

The docker image should accept valid YAML files.

### Error Logs
```
Error: /usr/local/apisix/conf/config.yaml does not contain 'role: data_plane'. Deployment role must be set to 'data_plane' for standalone mode.
Please refer to the APISIX documentation for deployment modes: https://apisix.apache.org/docs/apisix/deployment-modes/
```

### Steps to Reproduce

Run apisix via the docker image, with config set to something like this:
```yaml
 role: "data_plane"
  role_data_plane:
    config_provider: yaml
```

### Environment

Apisix docker image, tag `3.12.0`

### PR DESCRIPTION
**Pull request by janiussyafiq**
### Description

This PR fixes a bug in the Docker standalone configuration check script (check_standalone_config.sh) where valid YAML configurations would fail validation due to rigid pattern matching. and the case where `APISIX_PROFILE` does not respected. This PR also included necessary test cases.

#### Which issue(s) this PR fixes:

Fixes #12427 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: docker/utils/check_standalone_config.sh [hunk 1]
```diff
@@ -16,20 +16,30 @@
...
+if ! grep -E -q '["'\'']?role_data_plane["'\'']?:' "$CONF_FILE"; then
+    echo "Error: $CONF_FILE does not contain 'role_data_plane:'."
     echo "Please refer to the APISIX documentation for deployment modes: https://apisix.apache.org/docs/apisix/deployment-modes/"
     exit 1
 fi
 
-if ! grep -q 'config_provider: yaml' "${PREFIX}/conf/config.yaml"; then
-    echo "Error: ${PREFIX}/conf/config.yaml does not contain 'config_provider: yaml'. Config provider must be set to 'yaml' for standalone mode."
+if ! grep -E -q '["'\'']?config_provider["'\'']?:\s*["'\'']?yaml["'\'']?' "$CONF_FILE"; then
+    echo "Error: $CONF_FILE does not contain 'config_provider: yaml'. Config provider must be set to 'yaml' for standalone mode."
```
Comment (shreemaan-abhishek) [inline docker/utils/check_standalone_config.sh]: please add tests that cover the changes you made in this file.

Comment (janiussyafiq) [reply docker/utils/check_standalone_config.sh]: could you provide more context on what tests are needed since i've written a few? do you mean the $CONF_FILE returning the correct file name?

File: docker/utils/check_standalone_config.sh [hunk 2]
```diff
@@ -16,20 +16,30 @@
 # limitations under the License.
 #
 
-if ! grep -q 'role: data_plane' "${PREFIX}/conf/config.yaml"; then
-    echo "Error: ${PREFIX}/conf/config.yaml does not contain 'role: data_plane'. Deployment role must be set to 'data_plane' for standalone mode."
+CONF_FILE="${PREFIX}/conf/config.yaml"
```
Comment (nic-6443) [inline docker/utils/check_standalone_config.sh]: I suggest that we should not validate `config.yaml` through the shell, as it is prone to errors. We can move the checking logic to ops.lua, so that we can validate `config.yaml` in a semantic way:
https://github.com/apache/apisix/blob/adf2ea1573a17dee97ff8a4ad2df835f3ba8a862/apisix/cli/ops.lua#L179-L186
Here, check the environment variables and fields in the `yaml_conf` object.

File: docker/debian-dev/docker-entrypoint.sh
Comment (shreemaan-abhishek) [inline docker/debian-dev/docker-entrypoint.sh:1]: Image

you have changed the mode of this file, why?

Comment (janiussyafiq) [reply docker/debian-dev/docker-entrypoint.sh:1]: might've changed it when i did local testing, will revert it back

File: t/cli/test_standalone_docker.sh [hunk 3]
```diff
@@ -0,0 +1,216 @@
...
+if ! run_docker_test "true"; then
+    echo "failed: single quoted \"role: 'data_plane'\" was rejected"
+    exit 1
+fi
+
+echo "passed: single-quoted format accepted"
+
+# flow syntax
+echo '
+deployment: {"role": "data_plane", "role_data_plane": {"config_provider": "yaml"}}
```
Comment (shreemaan-abhishek) [inline t/cli/test_standalone_docker.sh:117]: this is neither a valid json nor a valid yaml, why would using this config not fail?

File: t/cli/test_standalone_docker.sh [hunk 4]
```diff
@@ -0,0 +1,216 @@
...
+standalone() {
+    clean_up
+    docker rm -f apisix-test-standalone 2>/dev/null || true
+    git checkout conf/apisix.yaml
+}
+
+DOCKER_IMAGE="${DOCKER_IMAGE:-apache/apisix:master-debian-dev}"
+trap standalone EXIT
+
+make build-on-debian-dev
```
Comment (shreemaan-abhishek) [inline t/cli/test_standalone_docker.sh]: This is going to significantly increase the duration of the CI. We can take one of the following actions to avoid this:

- use prebuilt image (image built from previous push) instead of building image while running the test.
- run this test only on master branch
  - but this will require further more changes (e.g: a separate GitHub actions workflow)
  - and we won't be able to detect regressions before commit
- run this test on a different GitHub actions workflow and only run them if any of the files related to this feature (ops.lua, docker-entrypoint.sh, etc) change.

Comment (shreemaan-abhishek) [reply t/cli/test_standalone_docker.sh]: 3rd option sounds good to me

File: t/cli/test_standalone_docker.sh (hunk 3 above)
Comment (janiussyafiq) [reply t/cli/test_standalone_docker.sh:117]: https://www.yamllint.com/ tried the syntax here, and it works - copy this code block
`deployment: {"role": "data_plane", "role_data_plane": {"config_provider": "yaml"}}
apisix:
    node_listen: 9080`
i think this also addressed here: https://github.com/apache/apisix/issues/12427

File: t/cli/test_standalone_docker.sh (hunk 4 above)
Comment (janiussyafiq) [reply t/cli/test_standalone_docker.sh]: opt 1: won't work, i've discussed with @nic-6443, since the older image still rely on the script that is decided to be removed `check_standalone_config.sh`, so test will fail
as for opt 2 and 3, can try those solution, i'm more leaning towards opt 3 wdyt?

Comment (janiussyafiq) [reply t/cli/test_standalone_docker.sh]: will try implementing 3rd option thanks!

File: t/cli/test_standalone_docker.sh (hunk 3 above)
Comment (shreemaan-abhishek) [reply t/cli/test_standalone_docker.sh:117]: interesting..

**Review by nic-6443 — APPROVED** [review]

**Review by Baoyuantop — APPROVED** [review]
