### PR TITLE
fix: avoid initialising stream plugins in http subsystem

### LINKED ISSUE #12458: bug: the stream plugins should not be loaded in the http subsystem
### Current Behavior

In https://github.com/apache/apisix/pull/12383#discussion_r2221865942, we found that the stream plugin was loaded incorrectly in the http subsystem. This is obviously incorrect behavior.

Whether the http plugin will be loaded in the stream subsystem was not found in the PR's processing flow and needs to be verified in the fix.

### Expected Behavior

Only http plugins should be loaded in the http subsystem. 
Only stream plugins should be loaded in the stream subsystem.

### Error Logs

_No response_

### Steps to Reproduce

1. Use https://github.com/apache/apisix/pull/12383 or wait for the merged code
2. Enable Prometheus plugin in stream and http
3. Start apisix and access the metrics API
4. Check the error log. You should be able to find the logs we added in PR https://github.com/apache/apisix/pull/12383/files#diff-390eaff60bfa1071dd1850bce9c7689452eaa13f07bf45a927921ecf05886d1bR237 in the error log.

### Environment

- APISIX version (run `apisix version`): master or https://github.com/apache/apisix/pull/12383
- Operating system (run `uname -a`): ubuntu 24.10
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by shreemaan-abhishek**
### Description

Fixes #12458

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/plugin.lua [hunk 1]
```diff
@@ -197,6 +197,13 @@ local function load_plugin(name, plugins_list, plugin_type)
     plugin.attr = plugin_attr(name)
     core.table.insert(plugins_list, plugin)
 
+    -- Don't initialize stream plugins in the HTTP subsystem.
+    -- The modules are loaded for schema validation (admin API),
+    -- but init/workflow_handler functions must only run in the stream subsystem.
+    if plugin_type == PLUGIN_TYPE_STREAM and is_http then
+        return
```
Comment (Baoyuantop) [inline apisix/plugin.lua:209]: Will the stream plugin be destroyed in the HTTP subsystem? If so, the `destroy()` function is called, but `init()` is skipped. Is there a potential issue of lifecycle asymmetry?

Comment (shreemaan-abhishek) [reply apisix/plugin.lua:209]: such a great catch, I have fixed it.
