### PR TITLE
fix(brotli): Preserve ETag and Last-Modified headers in Brotli-compressed response

### LINKED ISSUE #12707: bug: `ETag` and `Last-Modified` headers are not preserved when response is Brotli-compressed
### Current Behavior

The `ETag` and `Last-Modified` headers are cleared when the response is compressed by the Brotli plugin:
https://github.com/apache/apisix/blob/0c794a04998729ea732a6054ad3a973cb87eabc7/apisix/plugins/brotli.lua#L225-L226
https://github.com/apache/apisix/blob/0c794a04998729ea732a6054ad3a973cb87eabc7/apisix/core/response.lua#L158-L166

### Expected Behavior

The `ETag` and `Last-Modified` headers from the upstream server should be preserved even though the response is Brotli-compressed. Clearing these headers is not required because if the source content has not changed, then the compressed content would not change either and the browser can avoid requesting the unchanged content from the server again.

The [APISIX `gzip` plugin](https://github.com/apache/apisix/blob/master/apisix/plugins/gzip.lua) appears _not_ to clear these headers. This also indicates that clearing these headers is not required.

### Error Logs

_No response_

### Steps to Reproduce

1. Build an APISIX image with the Brotli shared libraries as mentioned [in the documentation](https://apisix.apache.org/docs/apisix/plugins/brotli/#prerequisites).
2. Prepare an upstream server that returns a response with the `ETag` and `Last-Modified` headers.
3. Create an APISIX route to the upstream server that enables the Brotli plugin.
4. Make a request to the upstream server via APISIX with the `Accept-Encoding` header set to `br` and observe that the `ETag` and `Last-Modified` headers are removed.

### Environment

- APISIX version (run `apisix version`): `3.9.1`
- Operating system (run `uname -a`): Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): `nginx version: openresty/1.25.3.1`
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): Not relevant
- APISIX Dashboard version, if relevant: Not relevant
- Plugin runner version, for issues related to plugin runners: Not relevant
- LuaRocks version, for installation issues (run `luarocks --version`): Not relevant

### PR DESCRIPTION
**Pull request by yuweizzz**
### Description

Downgrade etag when in needed.

#### Which issue(s) this PR fixes:

Fixes #12707

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/plugins/brotli.lua [hunk 1]
```diff
@@ -152,6 +152,30 @@ local function check_accept_encoding(ctx)
...
+    local matched, err = ngx.re.match(etag, regex, "jo")
+    if not matched then
+        -- not standard etag, no quote
+        ngx.header.etag = nil
+        return
+    end
+
+    if not matched[1] then
+        -- strong etag, downgrade it
+        ngx.header.etag = [[W/"]] .. matched[2] .. [["]]
```
Comment (Baoyuantop) [inline apisix/plugins/brotli.lua]: It is recommended to use core.response.set_header to maintain consistent code style.

File: apisix/plugins/brotli.lua [hunk 2]
```diff
@@ -152,6 +152,30 @@ local function check_accept_encoding(ctx)
...
 
 
+local function weak_etag_header()
+    local etag = ngx.header.etag 
+    if not etag then
+        return
+    end
+
+    local regex = [[^(W/)?"(.*)"$]]
+    local matched, err = ngx.re.match(etag, regex, "jo")
```
Comment (Baoyuantop) [inline apisix/plugins/brotli.lua:162]: The err variable is declared but never used; if a regular expression match fails, an error should be logged.

File: apisix/plugins/brotli.lua (hunk 1 above)
Comment (yuweizzz) [reply apisix/plugins/brotli.lua]: done.

File: apisix/plugins/brotli.lua (hunk 2 above)
Comment (yuweizzz) [reply apisix/plugins/brotli.lua:162]: done.

File: apisix/plugins/brotli.lua (hunk 1 above)
Comment (Baoyuantop) [reply apisix/plugins/brotli.lua]: Hi @yuweizzz, similar issues exist in other parts of the code; please correct them all.

Comment (yuweizzz) [reply apisix/plugins/brotli.lua]: I will check it again.

**Comment by yuweizzz** [comment]
@Baoyuantop

**Comment by yuweizzz** [comment]
any update?

**Review by Baoyuantop — APPROVED** [review]

**Review by moonming — CHANGES_REQUESTED** [review]
Hi @yuweizzz, thanks for fixing the Brotli ETag preservation issue (#12707)!

Downgrading strong ETags to weak ETags after compression is the correct behavior per HTTP spec (RFC 7232). With 6 reviews, this looks well-discussed.

**To confirm merge readiness**:
1. Are all review comments addressed?
2. Does the fix also handle the Last-Modified header correctly alongside ETag?
3. Tests look present — do they cover both strong and weak ETag inputs?

This seems close to ready. Thank you!

**Comment by yuweizzz** [comment]
yes, I confirm that all the part your mentioned has fixed now.

**Comment by yuweizzz** [comment]
any update?

**Review by shreemaan-abhishek — APPROVED** [review]

**Review by moonming — APPROVED** [review]
