### PR TITLE
fix(discovery/kubernetes): adjust id length

### LINKED ISSUE #12479: help request: about discovery kubernetes multi-cluster mode
### Description

```
apisix:
  node_listen: 9080
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

nginx_config:
  error_log_level: debug

discovery:
  kubernetes:
  - id: prod1
    service:
      schema: https
      host: "a.example.com"
      port: "443"
    client:
      token: |-
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    default_weight: 50
    namespace_selector:
      match:
        - ".*"
    shared_size: 1m
    watch_endpoint_slices: false
  - id: prod2
    service:
      schema: https
      host: "b.example.com"
      port: "443"
    client:
      token: |-
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    default_weight: 50
    namespace_selector:
      match:
        - ".*"
    shared_size: 1m
    watch_endpoint_slices: false 

deployment:
  admin:
    allow_admin:  
      - 0.0.0.0/0

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"     
    timeout: 30

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
```

The above is my apisix configuration file. I am doing automatic discovery for multiple k8s clusters, but following the above configuration will result in the following error
```
docker logs -f 42aa972214e6
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init
failed to read local yaml config of apisix: invalid discovery kubernetes configuration: object matches none of the required
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init
failed to read local yaml config of apisix: invalid discovery kubernetes configuration: object matches none of the required
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init
failed to read local yaml config of apisix: invalid discovery kubernetes configuration: object matches none of the required
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init
failed to read local yaml config of apisix: invalid discovery kubernetes configuration: object matches none of the required
```

If only one cluster is possible, as configured below
```
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

nginx_config:
  error_log_level: debug

discovery:
  kubernetes:
  - id: prod1
    service:
      schema: https
      host: "a.example.com"
      port: "443"
    client:
      token: |-
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    default_weight: 50
    namespace_selector:
      match:
        - ".*"
    shared_size: 1m
    watch_endpoint_slices: false

deployment:
  admin:
    allow_admin:  
      - 0.0.0.0/0

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"     
    timeout: 30

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
```

I would like to know if there is a problem with my configuration or if Apisix does not support automatic discovery of services in multiple Kubernetes clusters

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by SkyeYoung**
### Description

This PR is designed to solve problems found in #12479:

1. `discovery.kubernetes.id` needs to support more than 8 characters.

These designs were originally artificially limited, and there was [a lack of discussion](https://github.com/apache/apisix/pull/7895) at the time. 

Considering that `id`s have common cases like `aws-jp-common` and `aws-sgp-common`, the following adjustments were made in this PR:

1. Adjust `discovery.kubernetes.id` to support a maximum of 64 characters.

#### Which issue(s) this PR fixes:

Fixes #12479

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/discovery/kubernetes/schema.lua [hunk 1]
```diff
@@ -17,7 +17,8 @@
 
 local host_patterns = {
     { pattern = [[^\${[_A-Za-z]([_A-Za-z0-9]*[_A-Za-z])*}$]] },
-    { pattern = [[^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$]] },
+    { pattern = [[^[A-Za-z0-9]([-A-Za-z0-9]*[A-Za-z0-9])?]] ..
```
Comment (moonming) [inline apisix/discovery/kubernetes/schema.lua]: according to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names, we don't need to support uppercase letters

Comment (SkyeYoung) [reply apisix/discovery/kubernetes/schema.lua]: @moonming This document is for object names in Kubernetes, and the API server endpoint (e.g., [`https://5E1D0CEXAMPLEA591B746AFC5AB30262.yl4.us-west-2.eks.amazonaws.com`](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-eks-cluster.html#:~:text=master%20key%20(CMK).-,Endpoint,as%20https%3A//5E1D0CEXAMPLEA591B746AFC5AB30262.yl4.us%2Dwest%2D2.eks.amazonaws.com.,-Id)) is not a Kubernetes object name.

Comment (SkyeYoung) [reply apisix/discovery/kubernetes/schema.lua]: rollbacked

Comment (Baoyuantop) [reply apisix/discovery/kubernetes/schema.lua]: @SkyeYoung, please modify the corresponding description information.

**Review by membphis — APPROVED** [review]

File: apisix/discovery/kubernetes/schema.lua (hunk 1 above)
Comment (SkyeYoung) [reply apisix/discovery/kubernetes/schema.lua]: @Baoyuantop  What descriptions need to be adjusted? 🤔

**Review by Baoyuantop — APPROVED** [review]
