### PR TITLE
fix: install apisix-runtime when install APISIX from source

### LINKED ISSUE #10684: bug: apisix doesn't work, 'resty.events.compat' not found
### Current Behavior

i follow the source installation guild(checkout master), https://apisix.apache.org/docs/apisix/building-apisix/
then start the apisix, it will throw a error like `'resty.events.compat' not found:`

if i checkout to the branch before, it works fine, looks like https://github.com/apache/apisix/pull/10550 makes this

### Expected Behavior

start apisix success, and no errors

### Error Logs
```shell
2023/12/21 11:45:49 [info] 4409#48488: *9 [lua] init.lua:114: http_init_worker(): random test in [1, 10000]: 9291, context: init_worker_by_lua*
2023/12/21 11:45:49 [error] 4406#48485: init_worker_by_lua error: /Users/vacant/apisix/apisix/events.lua:68: module 'resty.events.compat' not found:
	no field package.preload['resty.events.compat']
	no file '/Users/vacant/apisix//deps/share/lua/5.1/resty/events/compat.lua'
	no file '/Users/vacant/apisix//deps/share/lua/5.1/resty/events/compat/init.lua'
	no file '/Users/vacant/apisix/resty/events/compat.lua'
	no file '/Users/vacant/apisix/resty/events/compat/init.lua'
	no file '/opt/homebrew/Cellar/openresty/1.21.4.2_1/site/lualib/resty/events/compat.ljbc'
```

### Steps to Reproduce

follow the source installation guild
https://apisix.apache.org/docs/apisix/building-apisix/
```shell
curl https://raw.githubusercontent.com/apache/apisix/master/utils/install-dependencies.sh -sL | bash -

git checkout master

apisix stop

make deps
sudo make install

apisix start

cat logs/error.log
```

### Environment

- APISIX version (run `apisix version`): 3.7.0
- Operating system (run `uname -a`): Darwin MasterNode.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 arm64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.2
- LuaRocks version, for installation issues (run `luarocks --version`): 3.9.2

### LINKED ISSUE #10775: bug: ./utils/install-dependencies.sh use a wrong link about linux-install-luarocks.sh
### Current Behavior

the script `./utils/install-dependencies.sh` on tag `3.7.0`  will use  `linux-install-luarocks.sh` which is on master.
https://github.com/apache/apisix/blob/ec77fb8ca2e797aa90d6547a1e323d4f40e27527/utils/install-dependencies.sh#L115

### Expected Behavior

the script `./utils/install-dependencies.sh` on tag `3.7.0`  should use  `linux-install-luarocks.sh` which is on tag `3.7.0`.

### Error Logs

_No response_

### Steps to Reproduce

1.  ./utils/install-dependencies.sh (on tag 3.7.0)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by Vacant2333**
### Description

we have replace openresty by apisix-runtime now, but t he user guide and `install-dependencies.sh` have not been update

Fixes https://github.com/apache/apisix/issues/10684

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

Fixes #10775

### CODE REVIEW

File: utils/install-dependencies.sh [hunk 1]
```diff
@@ -83,8 +79,9 @@ function install_dependencies_with_apt() {
     fi
     sudo apt-get update
 
-    # install OpenResty and some compilation tools
-    sudo apt-get install -y git openresty curl openresty-openssl111-dev make gcc libpcre3 libpcre3-dev libldap2-dev unzip
+    # install some compilation tools
+    sudo apt-get install -y curl make gcc g++ cpanminus libpcre3 libpcre3-dev libldap2-dev unzip openresty-zlib-dev openresty-pcre-dev
+    # get the APISIX_RUNTIME from .requirements
```
Comment (Vacant2333) [inline utils/install-dependencies.sh:84]: this may need be removed

File: utils/install-dependencies.sh [hunk 2]
```diff
@@ -19,6 +19,8 @@
 
 set -ex
 
+source .requirements
```
Comment (Vacant2333) [inline utils/install-dependencies.sh:22]: shoude we consider that the user run the shell in `utils/`

File: utils/install-dependencies.sh [hunk 3]
```diff
@@ -45,31 +45,25 @@ function install_dependencies_with_aur() {
...
-        # install OpenResty and some compilation tools
-        # shellcheck disable=SC2086
-        sudo yum install -y openresty $common_dep
+    sudo yum-config-manager --add-repo "https://openresty.org/package/${1}/openresty.repo"
+    if [[ "${1}" == "centos" ]]; then
+        sudo yum -y install centos-release-scl
+        sudo yum -y install devtoolset-9 patch wget
+        set +eu
+        source scl_source enable devtoolset-9
+        set -eu
```
Comment (moonming) [inline utils/install-dependencies.sh:54]: What do these dependencies do? There was no such thing before

File: Makefile [hunk 4]
```diff
@@ -40,13 +40,17 @@ ENV_DOCKER             ?= docker
 ENV_DOCKER_COMPOSE     ?= docker-compose --project-directory $(CURDIR) -p $(project_name) -f $(project_compose_ci)
 ENV_NGINX              ?= $(ENV_NGINX_EXEC) -p $(CURDIR) -c $(CURDIR)/conf/nginx.conf
 ENV_NGINX_EXEC         := $(shell command -v openresty 2>/dev/null || command -v nginx 2>/dev/null)
-ENV_OPENSSL_PREFIX     ?= $(addprefix $(ENV_NGINX_PREFIX), openssl3)
+ENV_OPENSSL_PREFIX     ?= /usr/local/openresty/openssl3
```
Comment (shreemaan-abhishek) [inline Makefile:43]: why change this?

File: utils/install-dependencies.sh [hunk 5]
```diff
@@ -45,31 +45,25 @@ function install_dependencies_with_aur() {
...
     fi
+    sudo yum install -y  \
+        gcc gcc-c++ curl wget unzip xz gnupg perl-ExtUtils-Embed cpanminus patch \
+        perl perl-devel pcre pcre-devel openldap-devel \
+        openresty-zlib-devel openresty-pcre-devel
```
Comment (moonming) [inline utils/install-dependencies.sh:59]: What do these dependencies do? There was no such thing before

File: Makefile [hunk 6]
```diff
@@ -126,12 +128,12 @@ endef
 .PHONY: runtime
 runtime:
 ifeq ($(ENV_NGINX_EXEC), )
-ifeq ("$(wildcard /usr/local/openresty-debug/bin/openresty)", "")
+ifeq ("$(wildcard /usr/local/openresty/bin/openresty)", "")
```
Comment (shreemaan-abhishek) [inline Makefile:131]: ditto

File: Makefile [hunk 7]
```diff
@@ -126,12 +128,12 @@ endef
...
 	@$(call func_echo_warn_status, "WARNING: OpenResty not found. You have to install OpenResty and add the binary file to PATH before install Apache APISIX.")
 	exit 1
 else
-	$(eval ENV_NGINX_EXEC := /usr/local/openresty-debug/bin/openresty)
-	@$(call func_echo_status, "Use openresty-debug as default runtime")
+	$(eval ENV_NGINX_EXEC := /usr/local/openresty/bin/openresty)
```
Comment (shreemaan-abhishek) [inline Makefile:135]: ditto

File: utils/install-dependencies.sh [hunk 8]
```diff
@@ -45,31 +45,25 @@ function install_dependencies_with_aur() {
...
 }
 
 # Install dependencies on ubuntu and debian
 function install_dependencies_with_apt() {
     # add OpenResty source
     sudo apt-get update
-    sudo apt-get -y install software-properties-common wget lsb-release
+    sudo apt-get -y install software-properties-common wget lsb-release gnupg patch
```
Comment (moonming) [inline utils/install-dependencies.sh:66]: ditto

File: utils/install-dependencies.sh [hunk 9]
```diff
@@ -83,8 +77,8 @@ function install_dependencies_with_apt() {
     fi
     sudo apt-get update
 
-    # install OpenResty and some compilation tools
-    sudo apt-get install -y git openresty curl openresty-openssl111-dev make gcc libpcre3 libpcre3-dev libldap2-dev unzip
+    # install some compilation tools
+    sudo apt-get install -y curl make gcc g++ cpanminus libpcre3 libpcre3-dev libldap2-dev unzip openresty-zlib-dev openresty-pcre-dev
```
Comment (moonming) [inline utils/install-dependencies.sh:81]: ditto

File: docs/zh/latest/building-apisix.md [hunk 10]
```diff
@@ -44,23 +44,22 @@ import TabItem from '@theme/TabItem';
...
+然后，你可以运行以下命令，从 Github 克隆 APISIX 源码：
 
 ```shell
-APISIX_VERSION='3.7.0'
-mkdir apisix-${APISIX_VERSION}
+git clone --depth 1 --branch ${APISIX_VERSION} https://github.com/apache/apisix.git apisix-${APISIX_VERSION}
 ```
 
-现在，你可以运行以下命令，从 Github 克隆 APISIX 源码：
+现在，切换到 APISIX 源码的目录，你可以通过以下命令安装依赖项：
```
Comment (moonming) [inline docs/zh/latest/building-apisix.md:59]: No dependencies in the command line

File: ci/redhat-ci.sh [hunk 11]
```diff
@@ -36,12 +36,9 @@ install_dependencies() {
 
     # install apisix-runtime to make apisix's rpm test work
     yum install -y yum-utils && yum-config-manager --add-repo https://openresty.org/package/centos/openresty.repo
-    rpm --import https://repos.apiseven.com/KEYS
-    yum -y install https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
-
-    export luajit_xcflags="-DLUAJIT_ASSERT -DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT -O0"
-    export debug_args=--with-debug
+    yum install -y openresty-pcre-devel openresty-zlib-devel
```
Comment (moonming) [inline ci/redhat-ci.sh:39]: why add this?

File: docs/en/latest/building-apisix.md [hunk 12]
```diff
@@ -45,22 +45,22 @@ To build and package APISIX for a specific platform, see [apisix-build-tools](ht
...
-Save the APISIX version to an environment variable to be used next:
+Then, you can run the following command to clone the APISIX source code from Github:
 
 ```shell
-APISIX_VERSION='3.7.0'
+git clone --depth 1 --branch ${APISIX_VERSION} https://github.com/apache/apisix.git apisix-${APISIX_VERSION}
 ```
 
-Clone the APISIX source code of this version into a new directory `apisix-APISIX_VERSION`:
+Now, by changing to the directory of the APISIX source code, you can install the dependencies with the following command:
```
Comment (shreemaan-abhishek) [inline docs/en/latest/building-apisix.md:60]: I don't see any commands to install dependencies of apisix.

File: ci/redhat-ci.sh [hunk 13]
```diff
@@ -36,12 +36,9 @@ install_dependencies() {
 
     # install apisix-runtime to make apisix's rpm test work
     yum install -y yum-utils && yum-config-manager --add-repo https://openresty.org/package/centos/openresty.repo
-    rpm --import https://repos.apiseven.com/KEYS
-    yum -y install https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
-
-    export luajit_xcflags="-DLUAJIT_ASSERT -DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT -O0"
-    export debug_args=--with-debug
```
Comment (monkeyDluffy6017) [inline ci/redhat-ci.sh:43]: Why do you remove `export debug_args=--with-debug`, all debug log will be suppressed

File: Makefile [hunk 14]
```diff
@@ -40,13 +40,17 @@ ENV_DOCKER             ?= docker
...
 ENV_NGINX_EXEC         := $(shell command -v openresty 2>/dev/null || command -v nginx 2>/dev/null)
-ENV_OPENSSL_PREFIX     ?= $(addprefix $(ENV_NGINX_PREFIX), openssl3)
+ENV_OPENSSL_PREFIX     ?= /usr/local/openresty/openssl3
 ENV_LUAROCKS           ?= luarocks
 ## These variables can be injected by luarocks
 ENV_INST_PREFIX        ?= /usr
 ENV_INST_LUADIR        ?= $(ENV_INST_PREFIX)/share/lua/5.1
 ENV_INST_BINDIR        ?= $(ENV_INST_PREFIX)/bin
 ENV_HOMEBREW_PREFIX    ?= /usr/local
+ENV_RUNTIME_VER		   ?= $(shell $(ENV_NGINX_EXEC) -V 2>&1 | tr ' ' '\n'  | grep 'APISIX_RUNTIME_VER' | cut -d '=' -f2)
```
Comment (monkeyDluffy6017) [inline Makefile:50]:
```suggestion
ENV_RUNTIME_VER	?= $(shell $(ENV_NGINX_EXEC) -V 2>&1 | tr ' ' '\n'  | grep 'APISIX_RUNTIME_VER' | cut -d '=' -f2)
```

Comment (monkeyDluffy6017) [inline Makefile:50]:
```suggestion
ENV_HOMEBREW_PREFIX    ?= /usr/local
ENV_RUNTIME_VER	     ?= $(shell $(ENV_NGINX_EXEC) -V 2>&1 | tr ' ' '\n'  | grep 'APISIX_RUNTIME_VER' | cut -d '=' -f2)
```

File: ci/centos7-ci.sh [hunk 15]
```diff
@@ -43,9 +42,9 @@ install_dependencies() {
 
     # install openresty to make apisix's rpm test work
     yum install -y yum-utils && yum-config-manager --add-repo https://openresty.org/package/centos/openresty.repo
-    export luajit_xcflags="-DLUAJIT_ASSERT -DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT -O0"
-    export debug_args=--with-debug
```
Comment (monkeyDluffy6017) [inline ci/centos7-ci.sh:47]: Why do you remove export debug_args=--with-debug, all debug log will be suppressed

File: utils/install-dependencies.sh [hunk 16]
```diff
@@ -45,31 +45,25 @@ function install_dependencies_with_aur() {
...
-        # shellcheck disable=SC2086
-        sudo yum install -y apisix-runtime $common_dep
-    else
-        # add OpenResty source
-        sudo yum-config-manager --add-repo "https://openresty.org/package/${1}/openresty.repo"
-
-        # install OpenResty and some compilation tools
-        # shellcheck disable=SC2086
-        sudo yum install -y openresty $common_dep
+    sudo yum-config-manager --add-repo "https://openresty.org/package/${1}/openresty.repo"
```
Comment (monkeyDluffy6017) [inline utils/install-dependencies.sh:48]: No need apisix repo any more?

File: utils/install-dependencies.sh [hunk 17]
```diff
@@ -107,12 +103,46 @@ function multi_distro_installation() {
...
+    rm build-apisix-runtime.sh
+}
+
 # Install LuaRocks
 function install_luarocks() {
-    curl https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh -sL | bash -
+    if [ -f "./utils/linux-install-luarocks.sh" ]; then
+        ./utils/linux-install-luarocks.sh
+    elif [ -f "./linux-install-luarocks.sh" ]; then
+        ./linux-install-luarocks.sh
```
Comment (monkeyDluffy6017) [inline utils/install-dependencies.sh:141]: The file `linux-install-luarocks.sh` is under the directory `utils`, why need this judge?

File: utils/install-dependencies.sh (hunk 3 above)
Comment (AlinsRan) [reply utils/install-dependencies.sh:54]: Previously, we used to use compiled apisix runtime repo packages, but now building from source code requires these dependencies.
Centos requires a higher version of gcc..

File: utils/install-dependencies.sh (hunk 5 above)
Comment (AlinsRan) [reply utils/install-dependencies.sh:59]: Previously, apsix-runtime was not built from source code.

File: ci/centos7-ci.sh (hunk 15 above)
Comment (AlinsRan) [reply ci/centos7-ci.sh:47]: `./build-apisix-runtime.sh latest` contains debug information.

Without `with-debug`, our test cases cannot pass.

File: utils/install-dependencies.sh (hunk 16 above)
Comment (AlinsRan) [reply utils/install-dependencies.sh:48]: yes

File: utils/install-dependencies.sh (hunk 8 above)
Comment (AlinsRan) [reply utils/install-dependencies.sh:66]: The reason is the same as before, unless we do not build from the apisix runtime source code.

File: Makefile (hunk 4 above)
Comment (AlinsRan) [reply Makefile:43]: By default, `ENV_ NGINX_ PREFIX` is empty.
Only when it is set, or when openssl3 dir is empty, it will take effect in the future

File: Makefile (hunk 7 above)
Comment (AlinsRan) [reply Makefile:135]: Do not install to openrest-debug

File: Makefile (hunk 6 above)
Comment (AlinsRan) [reply Makefile:131]: Do not install to openrest-debug

File: ci/redhat-ci.sh (hunk 11 above)
Comment (AlinsRan) [reply ci/redhat-ci.sh:39]: It is required to build the apisix-runtime.

File: utils/install-dependencies.sh (hunk 17 above)
Comment (AlinsRan) [reply utils/install-dependencies.sh:141]: The script can be executed separately in the `utils/` directory.

File: ci/redhat-ci.sh (hunk 13 above)
Comment (AlinsRan) [reply ci/redhat-ci.sh:43]: ./build-apisix-runtime.sh latest contains debug information.

Without with-debug, our test cases cannot pass.

File: docs/en/latest/building-apisix.md (hunk 12 above)
Comment (AlinsRan) [reply docs/en/latest/building-apisix.md]: Updated!

File: docs/zh/latest/building-apisix.md (hunk 10 above)
Comment (AlinsRan) [reply docs/zh/latest/building-apisix.md]: Updated!

File: utils/install-dependencies.sh (hunk 3 above)
Comment (moonming) [reply utils/install-dependencies.sh:54]: what's the reason to compile apisix-runtime from the source?

Comment (AlinsRan) [reply utils/install-dependencies.sh:54]: 1. Publishing the apisix-runtime repo will cause the installation of the apisix 3.7.0 debian package to fail.
2. CI is built using source code and should be consistent.
3. The apisix deb/rpm is a complete package and does not rely on the apisix runtime repo package, so building the apisix runtime is just an intermediate process.

File: docs/en/latest/building-apisix.md [hunk 18]
```diff
@@ -73,7 +67,7 @@ make deps
 make install
```
Comment (shreemaan-abhishek) [inline docs/en/latest/building-apisix.md:67]: make deps is required before running make install isn't it?

Comment (Vacant2333) [reply docs/en/latest/building-apisix.md:67]: yes, but make deps is before make install for this code now, i dont get that what do u mean

Comment (shreemaan-abhishek) [reply docs/en/latest/building-apisix.md:67]: oops my bad

**Review by shreemaan-abhishek — APPROVED** [review]
LGTM

**Review by moonming — APPROVED** [review]

**Review by juststillthinking — APPROVED** [review]
