### PR TITLE
fix: meta.filter in plugin doesn't work in response-rewrite plugin

### LINKED ISSUE #7852: bug: meta.filter in plugin doesn't work when we use some variable
### Current Behavior

When I use meta.filter in the plugin like this:

```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '{
  "plugins": {
    "file-logger": {
         "_meta": {
            "filter": [
                ["upstream_status", "~=", 200]
            ]
        },
      "path": "logs/file.log"
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org": 1
    }
  },
  "uri": "/*"
}'
```

What I expect is that when the upstream_status is not equal to 200, then we will write a log into the file.
But now, the plugin will be executed even if the upstream_status is 200.

Reason:
Because when we do the plugin filter, we can't get the upstream_status (because we hadn't sent a request to upstream), so the value of **`ngx.var.upstream_status` is nil**, and the filter is always matched.

https://github.com/apache/apisix/blob/47187faccd96d02773fb1c71980c8ca0ea838d6a/apisix/plugin.lua#L421-L458

### Expected Behavior

The meta.filter can work even if the plugin is run at the log phase.

### Error Logs

_No response_

### Steps to Reproduce

1. Create route

```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '{
  "plugins": {
    "file-logger": {
         "_meta": {
            "filter": [
                ["upstream_status", "~=", 200]
            ]
        },
      "path": "logs/file.log"
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org": 1
    }
  },
  "uri": "/*"
}'
```

2. Send two requests

```
curl localhost:9080/status/200 -v
```

```
curl localhost:9080/status/400 -v
```

3. We can see both requests are logged.
image

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by soulbird**
### Description

Fixes #7852

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/plugin.lua [hunk 1]
```diff
@@ -415,6 +415,11 @@ local function meta_filter(ctx, plugin_name, plugin_conf)
         return true
     end
 
+    local match_cache_key = ctx.conf_type .. plugin_name .. "meta_filter_matched"
```
Comment (tokers) [inline apisix/plugin.lua:418]: Use some separator like `#` before `meta_filter_matched` ?

File: apisix/plugin.lua [hunk 2]
```diff
@@ -920,6 +925,8 @@ function _M.run_plugin(phase, plugins, api_ctx)
         return api_ctx
     end
 
+    --local matched = meta_filter(ctx, name, plugin_conf)
```
Comment (tokers) [inline apisix/plugin.lua:928]: Remove this?

File: t/plugin/plugin.t [hunk 3]
```diff
@@ -525,3 +525,170 @@ passed
...
+--- response_headers
+test-header: error
+--- error_code: 502
+
+
+
+=== TEST 21: upstream_status = 200, disable response-rewrite plugin
+--- request
+GET /hello
+
```
Comment (tokers) [inline t/plugin/plugin.t:588]: Should check if the `x-test-upstream-status` doesn't exist.

File: apisix/plugin.lua [hunk 4]
```diff
@@ -433,6 +438,8 @@ local function meta_filter(ctx, plugin_name, plugin_conf)
                          " plugin_name: ", plugin_name)
         return true
     end
+
+    ctx[match_cache_key] = ok
```
Comment (starsz) [inline apisix/plugin.lua:442]: I think we can't cache the result of the filter. Since we have a different phase for every plugin like "rewrite", "access" e.g.

File: t/plugin/plugin.t (hunk 3 above)
Comment (soulbird) [reply t/plugin/plugin.t:590]: It doesn't make sense to check this, it's better to check if `test-header` exists.

File: apisix/plugin.lua (hunk 4 above)
Comment (soulbird) [reply apisix/plugin.lua:443]: `filter` works better at the plugin level and is executed at each phase, which will increase the difficulty for users to use.

File: apisix/plugin.lua [hunk 5]
```diff
@@ -415,6 +415,12 @@ local function meta_filter(ctx, plugin_name, plugin_conf)
         return true
     end
 
+    local match_cache_key =
+        ctx.conf_type .. "#" .. plugin_name .. "#meta_filter_matched"
```
Comment (spacewander) [inline apisix/plugin.lua:419]: Does this key work with multiple global_rules? They have the same conf_type.

Comment (soulbird) [reply apisix/plugin.lua:419]: Do you mean the scene where the `con_type` is the same and the `plugin_name` is different? I think my test case already contains. The `conf_type` is `route`.

Comment (spacewander) [reply apisix/plugin.lua:419]: @soulbird 
Multiple global rules will share the same conf_type
https://github.com/apache/apisix/blob/e2d0f0b16bb157412684a38b129d12acb4628d39/apisix/plugin.lua#L1003

Will this affect the cache of eval result?

Comment (soulbird) [reply apisix/plugin.lua]: There is indeed a problem, I adjusted `match_cache_key`, added some test case：https://github.com/apache/apisix/pull/8162/files#diff-29e2373df60fd8fc082317d17e636b6fa17c60459c1a691c5838f36b31cc486aR532-R567

File: t/plugin/plugin.t [hunk 6]
```diff
@@ -28,6 +28,7 @@ add_block_preprocessor(sub {
     $block;
 });
 
+repeat_each(1);
```
Comment (spacewander) [inline t/plugin/plugin.t:31]: https://github.com/apache/apisix/blob/e523132f35fe2eb7e1d06990d037f18f89c9dcba/t/APISIX.pm#L23
We already set it by default?

**Review by spacewander — APPROVED** [review]

**Comment by spacewander** [comment]
@soulbird 
> Fixes https://github.com/apache/apisix/issues/7852 https://github.com/apache/apisix/issues/8087

Need to use double fixes

**Comment by soulbird** [comment]
> @soulbird
> 
> > Fixes #7852 #8087
> 
> Need to use double fixes

My mistake, these two don't seem to be the same problem.

File: t/plugin/plugin.t [hunk 7]
```diff
@@ -520,8 +520,220 @@ passed
...
+=== TEST 25: proxy-rewrite plugin will set $http_foo_age, response-rewrite plugin return 403
+--- request
+GET /hello?age=18
+--- error_code: 403
+
+
+
+=== TEST 26: response-rewrite plugin disable, return 200
+--- request
+GET /hello
```
Comment (starsz) [inline t/plugin/plugin.t:689]: Missing any check ？

Comment (soulbird) [reply t/plugin/plugin.t:689]: By default, the 200 status code will be checked, so there is no need to repeatedly write.

**Review by starsz — APPROVED** [review]
