### PR TITLE
fix: upstream nodes cant't include ipv6 addr

### LINKED ISSUE #6905: bug: host schema validation doesn't support ipv6
### Current Behavior

image

### Expected Behavior

_No response_

### Error Logs

_No response_

### Steps to Reproduce

```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/*",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "[::1]:8882": 1
        }
    },
     "plugins":{"example-plugin":{"i": 123, "ip": "[::1]", "port": 8881}}
}'
```

### Environment

- APISIX version (run `apisix version`): 2.10.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

### PR DESCRIPTION
**Pull request by soulbird**
### Description
Make a simple modification to make the upstream nodes host support ipv6

Fixes #6905 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

### CODE REVIEW

File: apisix/schema_def.lua [hunk 1]
```diff
@@ -37,7 +37,7 @@ local id_schema = {
     }
 }
 
-local host_def_pat = "^\\*?[0-9a-zA-Z-._]+$"
+local host_def_pat = "^\\*?[0-9a-zA-Z-._\\[\\]:]+$"
```
Comment (zhendongcmss) [inline apisix/schema_def.lua:40]: Can validate ipv4/ipv6 more detail ?

File: t/APISIX.pm [hunk 2]
```diff
@@ -200,7 +200,7 @@ if ($version =~ m/\/apisix-nginx-module/) {
     $a6_ngx_directives = <<_EOC_;
     apisix_delay_client_max_body_check on;
     apisix_mirror_on_demand on;
-    wasm_vm wasmtime;
+    #wasm_vm wasmtime;
```
Comment (spacewander) [inline t/APISIX.pm:203]: Why remove that?

File: apisix/schema_def.lua (hunk 1 above)
Comment (spacewander) [reply apisix/schema_def.lua:40]: I would prefer to a simple regex check as a complex check is error-prone (may reject valid input)

Comment (membphis) [reply apisix/schema_def.lua:40]: IPv6 schema: https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L56

Comment (soulbird) [reply apisix/schema_def.lua:40]: > IPv6 schema: https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L56
> 
> can we reuse it?

Let my try

File: t/plugin/referer-restriction.t [hunk 3]
```diff
@@ -173,7 +173,6 @@ hello world
             local cases = {
                 "x.*",
                 "~y.xn",
-                "::1",
```
Comment (spacewander) [inline t/plugin/referer-restriction.t:176]: The `::1` is an invalid referer.

File: apisix/schema_def.lua (hunk 1 above)
Comment (zhendongcmss) [reply apisix/schema_def.lua:40]: My point that it is hard to use the same regular exprssion to valitate ipv4 and ipv6.

File: t/plugin/referer-restriction.t (hunk 3 above)
Comment (soulbird) [reply t/plugin/referer-restriction.t:176]: In fact, referer is a URL, and the current shcema check is not suitable. Maybe we need another PR to fix this

File: apisix/schema_def.lua (hunk 1 above)
Comment (soulbird) [reply apisix/schema_def.lua:40]: > I would prefer to a simple regex check as a complex check is error-prone (may reject valid input)

So I'm leaning towards a more conservative way of fixing it, like this currently. @zhendongcmss

**Review by spacewander — APPROVED** [review]

File: t/admin/upstream-array-nodes.t [hunk 4]
```diff
@@ -450,3 +450,38 @@ GET /t
...
+    location /t {
+        content_by_lua_block {
+            local t = require("lib.test_admin").test
+            local code, body = t('/apisix/admin/routes/1',
+                 ngx.HTTP_PUT,
+                 [[{
+                    "upstream": {
+                        "nodes": [
+                            {
+                                "host":"[::1]",
```
Comment (bzp2010) [inline t/admin/upstream-array-nodes.t:467]: Is it valid only when using object's node? What happens if I use an array pattern like `[::1]:8080`?

Comment (soulbird) [reply t/admin/upstream-array-nodes.t:467]: It will not affect object's node, see here: https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L308

**Review by bzp2010 — APPROVED** [review]

**Review by spacewander — APPROVED** [review]
