### PR TITLE
fix: reload plugin when plugin attribute is changed

### LINKED ISSUE #2655: bug: the plug-in can't be reload if it's function changed only.
### Issue description
the plug-in can't be reload with the ' apisix/admin/plugins/reload' if it's function changed only.
because the code  https://github.com/apache/apisix/blob/master/apisix/plugin.lua#L111

### Environment

* apisix version (cmd: `apisix version`): the current master branch
* OS: centos 7

### PR DESCRIPTION
**Pull request by spacewander**
Close #2655

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible?

### CODE REVIEW

File: apisix/plugin.lua [hunk 1]
```diff
@@ -51,6 +51,14 @@ local _M = {
 }
 
 
+local function plugin_attr(name)
+    -- TODO: get attr from synchronized data
```
Comment (juzhiyuan) [inline apisix/plugin.lua:55]: Is this TODO related to this PR?

**Review by juzhiyuan — APPROVED** [review]
LGTM

**Review by membphis — APPROVED** [review]
